### ISSUE TITLE
As an information manager / architect, I want to know what it means if a supplier earned a banner / is marked compliant

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/api-test-platform#105]
So I know what to expect when a supplier claims to to compliant. 

Context:
In the current situation a supplier can pass the STuF test platform tests with only implementing the required attributes according to the RGBZ / Stuf zaak document service specification.
This leads to a lack of clarity because as a buyer I don't know if a supplier supports every bit of the specification or only certain parts. In practice this leads to arguments with suppliers, wrong expectations and assumptions and errors during the implementation of connecting to applications with each other.

What I want:
An overview of test results for every supplier who submitted their software.
A banner for 100% compliance differentiated for every api version. A supplier can't get a full compliant banner without implementing the whole specification (all operations, attributes and behavior is implemented according to the specification).
If a supplier is not fully compliant, it should be visible for which parts a supplier is not compliant (which operations are not supported or which attributes are missing)
A list of banner types and a clear description of what it takes to 'earn' that banner. 

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by HenriKorver** [comment]
This issue is related with #76 and #72.

**Comment by HenriKorver** [comment]
My proposal is there wille be three types of badges:
* Green: All the tests are carried out and were succesful
* Orange: Not all the tests were carried out, but the ones that took place were succesful
* Red: One or more tests failed.

The badge is always linked to the test report in which one can see the details of the tests

**Comment by JanWillemKooi** [comment]
Deze vraag is beantwoord met het feit dat badges nu onderdeel zijn geworden van het ATP.
