### ISSUE TITLE
As API user of the API testvoorziening I want to manage my API tokens

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#112]
Currently API tokens can only be created by the admin. However as user of the API of the API testplatform I'd like to see and create API tokens for my account.

This will allow me to integrate the VNG API testplatform without asking the admin to add an API token for me.

**Toelichting**:
...

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by alextreme** [comment]
Deze is ter overweging, bij deze op de backlog maar het komt vaak voor dat je als gebruiker van een voorziening wat ook een API heeft dat je ook bij je eigen API tokens kan komen via de webinterface.

**Comment by alextreme** [comment]
Please point to the ATP API, to ensure it's clear where you can start using these tokens:

![Screenshot_2019-08-15_15-42-31](https://user-images.githubusercontent.com/226839/63098586-7ebd7300-bf73-11e9-86de-173571644d06.png)

**Comment by alextreme** [comment]
- Verwijs naar de ReDoc van de ATP API
 - Op de ReDoc verwijs naar de https://github.com/VNG-Realisatie/api-test-platform/
 - Hiervoor mist nog een tutorial over de API (en wellicht aanpassingen aan de API schema voor de duidelijkheid), een eenvoudige introductie op de github is welkom.

**Comment by stevenbal** [comment]
Ik heb [hier](https://github.com/VNG-Realisatie/api-test-platform/blob/master/tutorials/API.md) alvast een tutorial gemaakt voor de API
