### ISSUE TITLE
Als gemeente wil ik eenvoudig kunnen zien of een softwarepakket/dienst compliant is met een API-standaard

### ISSUE THREAD

**Issue by markbacker** [VNG-Realisatie/api-test-platform#141]
...zodat ik weet dat het pakket interoperabel is binnen mijn applicatielandschap

**Toelichting**:
Een gemeente moet zonder technische kennis kunnen beoordelen of een pakket compliant is met een API-standaard. De API-testvoorziening biedt hiervoor en rapportage waarin eenduidig wordt weergeven welke API-standaarden een pakket ondersteund. 

**Oplossingsrichting**:
Hiervoor moet goed worden nagedacht hoe dit zo begrijpelijk mogelijk aan de gemeente gepresenteerd kan worden:
* pakket is provider van ZGW API en ondersteund de resources ZTC, ZRC, ...  (compliancy wordt per resource weergegeven, bijvoorbeeld met een grote groene vink)
* pakket is consumer van ZGW API en vereist de resources ZTC, ZRC, ....  (
Hoe wordt de compliancy weergegeven? per resource of in één keer voor de set vereiste resources)

De Softwarecatagus wordt door gemeenten gebruikt bij een marktoriëntatie en biedt de zoek- en filtermogelijkheden om pakketten te selecteren en vergelijken. Leveranciers kunnen bij een pakketten registreren welke standaarden zij ondersteunen en tonen compliancy aan door een testrapport te uploaden.

Hoe gaat de ATV de testrapporten beschikbaar stellen aan leveranciers en gemeenten? 

1. ATV biedt - vergelijkbaar met het huidige STP - een download mogelijkheid van een testrapport. Leverancier biedt dit aan aan gemeenten, via de SWC
2. ATV biedt een API waarmee de testresultaten kunnen worden geraadpleegd. Lijkt ideaal, maar is niet zo eenvoudig. Vereist een wijziging in de SWC en creëert een wederzijdse afhankelijkheid. Andersom zal de ATV moeten gaan werken met de identifiers van de pakketten in de SWC

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by TCIMEddy** [comment]
zag ik voorbij komen en even op @HenriKorver naam gezet...voor prio en visie

**Comment by HenriKorver** [comment]
Ik pak m op als ik terug ben van vakantie

**Comment by HenriKorver** [comment]
@markbacker Dit is een voorbeeld van een badge die linkt naar een testrapportje op het testplatform

[![Status badge](https://img.shields.io/endpoint.svg?style=for-the-badge&amp;url=https://vng-staging.maykin.nl/api/v1/provider-run-shield/135/)](https://vng-staging.maykin.nl/server/d28ca332-f2ee-4b95-9918-d94a24da96c3)

En dit is de bijbehorende HTML snippet die je kunt plaatsen op de website van de Software Catalogus:
```
    <span display="block" height="20px" class="common__BadgeWrapper-sc-16zh6vt-3 fagfmg">
    <a href="https://vng-staging.maykin.nl/server/d28ca332-f2ee-4b95-9918-d94a24da96c3">
    <img style="width:100%" alt="" src="https://img.shields.io/endpoint.svg?style=for-the-badge&amp;
     url=https://vng-staging.maykin.nl/api/v1/provider-run-shield/135/"></span></a>
```
Deze test van de [Demo Api](https://github.com/maykinmedia/demo-api-component) draait elke nacht. Als de test faalt dan wordt de badge rood en veranderd succes in failed.

[![Status badge](https://img.shields.io/endpoint.svg?style=for-the-badge&amp;url=https://vng-staging.maykin.nl/api/v1/provider-run-shield/140/)](https://vng-staging.maykin.nl/server/15a3440a-819e-45ac-ae1f-3944d002a9be)

Volgens mij zou het mogelijk moeten zijn om een dergelijke badge in de Software Catalogus op te nemen. Of zie ik iets over het hoofd?

**Comment by markbacker** [comment]
@HenriKorver dit kan inderdaad gebruikt worden als optie 1 voor het beschikbaar stellen van testrapporten die ik noem. Het zal nu niet mogelijk zijn om in de SWC een badge te tonen, maar je kunt wel de link naar het testrapport opnemen.

In het testrapport mis ik de gegevens over de aanbieder van de service en wat met de test aangetoond is. Zie als voorbeeld het voorblad van een testrapport uit het STP, bijvoorbeeld https://www.softwarecatalogus.nl/sites/default/files/2019%20Q2%20build%2013966-Documentcreatie-2153561-testrapportage.pdf

Heb je ook een voorbeeld van een testrapport van een consumer? En hoe dan getoond wordt met welke services de consumer compliant is?

**Comment by HenriKorver** [comment]
@markbacker Ja inderdaad de rapportages missen nog gegevens over de aanbieder van de service en meer uitgebreide proza over wat precies met de test aangetoond is. Daarvoor zal ik nog een aparte user story opvoeren.

Bij deze een voorbeeld van een testrapport van een consumer (je ziet hier meteen al dat je behoefte hebt aan een korte beschrijving bij elke call)

![afbeelding](https://user-images.githubusercontent.com/37145898/57531307-69fc8e00-7339-11e9-8d3d-11e8f4813e66.png)

**Comment by HenriKorver** [comment]
Dit is inmiddels opgelost door Newman-rapportages en badges
