### ISSUE TITLE
As productowner I want to integrate the ZGW-testscripts with the test platform

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#154]
such that I can see that platform works in realistic cases

**Toelichting**:
...

**Oplossingsrichting**:

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by alextreme** [comment]
Waiting with this until authorization with the reference components is resolved (see also #86 )

**Comment by alextreme** [comment]
Can be placed into review after a partially-succesful run is yet again possible on vng-staging. Review will likely cause additional issues/improvements

**Comment by alextreme** [comment]
@AlviseSembenico could you check this using the ZGW api tests testscenario?

**Comment by AlviseSembenico** [comment]
I'm checking but trying to run the same tests and I got the result 
https://vng-staging.maykin.nl/server/8d5ebb3e-d885-463f-aa33-7e2a9ced89d8

**Comment by alextreme** [comment]
An update after Alvise and I have been looking at this again (with some help from Joeri). We've been updating the ZGW api test scenario to ensure this is at least runable again:

https://vng-staging.maykin.nl/server/5d3d818e-b13a-4883-a311-cda304c26b3a/

The Postman collection assigned to the 'ZGW api tests' has been updated by Alvise. There have been quite a lot of API changes in the last few weeks, currently only 14 calls of 163 calls succeed for the reference implementation.

I think waiting until the release candidant is the only way forward with this. For now I've asked Alvise to focus on the ZRC tests.

**Comment by stevenbal** [comment]
https://api-test.nl/server/50835e18-e350-4ad6-998a-0ec785251ed6/

**Comment by alextreme** [comment]
@stevenbal graag een voorbeeld van de ZGW scripts vanuit api-test of vng-staging, zodat duidelijk is dat het uitvoeren van de ZGW postman collection werkt zoals verwacht.

Momenteel is de verwachting dat de helft van de requests slagen en de helft niet. Voor de niet-slagende requests staan pullrequests bij ZGW uit.

**Comment by alextreme** [comment]
Optie is om live te gaan met de OAS-script. De 'volledige' houden we er voor nu alsnog in.

**Comment by alextreme** [comment]
Net zoals #265 ter review totdat ook de OAS-script testscenario slaagt op de ZGW referentieimplementatie github.

**Comment by alextreme** [comment]
Dienen aangepast te worden op basis van de definitieve versie 1.0 van de ZGW APIs

**Comment by JanWillemKooi** [comment]
Goed idee om deze scripts achterelkaar te runnen. Eigenlijk als 1 groot script. Starten met OS en daarna de rest.

**Comment by alextreme** [comment]
Huidige status:
https://api-test.nl/server/1/d60c848a-89e8-4c3f-8ac9-38780b85a43a/

357 van 394 assertions slagen. Dus we zijn er bijna...

**Comment by stevenbal** [comment]
Is inmiddels 2x achter elkaar groen
https://api-test.nl/server/1/6b5fe675-694d-4948-8896-5eae88d30ef0/306338e9-b9e4-48be-8e5a-bd3792f24c74/

**Comment by HenriKorver** [comment]
Hoera!!!!

**Comment by alextreme** [comment]
2x gelukt achter elkaar, daarna vermoedelijk gefaald vanwege gelijktijdige runs die handmatig zijn gestart. Daarna werkt het weer:

![Screenshot_2019-12-20_17-07-51](https://user-images.githubusercontent.com/226839/71267598-4b3c8c00-234b-11ea-8234-386b81885885.png)


Besproken met Steven dat het technisch mogelijk zou zijn om op basis van overeenkomstige environment variabelen van runs van dezelfde API deze runs in een queue op te zetten. Dan kan een run een stuk langer duren (ze moeten dan op hun beurt wachten) maar dan voorkom je wel dit probleem.
