### ISSUE TITLE
As productowner I want the website of the testplatform to have a proper domain name and have a production-ready environment

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#155]
such that it is organisation independant, timeless and ready for production

**Toelichting**:
At the moment the platform is hosted in the domain  `*.maykin.nl` (https://vng-staging.maykin.nl) which is not owned by VNG.  It should be migrated to another domain name of which VNG is the owner. 

This must be treated as a seperate issue compared with #170 

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by alextreme** [comment]
@HenriKorver to discuss the hosting within VNG with Roderick, prepare before sprint 7

**Comment by HenriKorver** [comment]
I claimed the domain name api-test.nl which seems very neutral and timeless. 
@alextreme How much work will it cost to switch to this domain name?

**Comment by alextreme** [comment]
@HenriKorver We will need to request a wildcard SSL certificate (due to the subdomain-proxy structure), but if you have access to the DNS configuration setting up a production environment, arranging the SSL certificate and configuring the domain is a matter of a couple of hours.

**Comment by alextreme** [comment]
This US also means installing the ATV on the Maykin server infrastructure (production).

**Comment by alextreme** [comment]
Domain DNS configuration has been configured at Hostnet. Henri is considering switching to TransIP, access to the DNS account would make things easier but isn't mandatory.

**Comment by alextreme** [comment]
Wildcard SSL certificate has been requested and approved.

**Comment by alextreme** [comment]
Here you go: https://api-test.nl

We still have to fill the database and verify the environment, this does depend on if you want to copy over all data from vng-staging or want to start 'fresh'. Do you have a preference @HenriKorver ?

**Comment by HenriKorver** [comment]
I can not register as a user due to problem with CAPTCHA

![afbeelding](https://user-images.githubusercontent.com/37145898/60027858-9167aa00-969e-11e9-9dca-5716fec7043d.png)

**Comment by HenriKorver** [comment]
> We still have to fill the database and verify the environment, this does depend on if you want to copy over all data from vng-staging or want to start 'fresh'. Do you have a preference @HenriKorver ?

Let me sleep one night over this question :-)

**Comment by alextreme** [comment]
New recaptcha API-key has been generated and installed on api-test.nl, registering now works as expected.

Lets discuss further details Thursday, verifying the environment with an empty database won't be of much use.
