### ISSUE TITLE
Als leverancier wil ik een banner of badge kunnen publiceren die linkt naar een testrapport op de testvoorziening voor de consumer

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#158]
zodat ik aan de buitenwereld kan laten zien in hoeverre mijn consumer compliant is met de Provider API.
Deze user story is complementair met user story #72 die gaat over badges voor de provider.

**Toelichting**:

**Oplossingsrichting**:
Voor badges van consumers is de kleur oranje ook nodig in geval de consumer niet alle scenario's uitgevoerd heeft (maar wel alle scenario's die wel zijn uitgevoerd zijn geslaagd).

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by alextreme** [comment]
This has been deployed to vng-staging and is ready for review in our eyes. The way this works is comparable to the badges for the providers, with the additional orange status for a non-completed-but-no-errors session:

![Screenshot_2019-07-10_14-34-37](https://user-images.githubusercontent.com/226839/60969497-f0285700-a31f-11e9-87e1-c0f24acb5390.png)

**Comment by alextreme** [comment]
Rename the label:
"VNG Test platform client"

to

"API Test Platform"

Do this also for the provider badges.

Rename
"No Errors, Not Completed"

to 

"Not Completed"

Nice-to-have: see if you can get the badges to be the same width

**Comment by HenriKorver** [comment]
Ik krijg een internal error als ik een consumer sessie voor de demo-api opstart: https://1566469413109-vng-staging.maykin.nl/demo-api/api/v2

**Comment by alextreme** [comment]
This was because the session type on vng-staging was configured incorrectly, it was still pointing to the ZGW demo-api URL:

https://vng-staging.maykin.nl/admin/testsession/sessiontype/5/change/

![Screenshot_2019-08-22_12-31-29](https://user-images.githubusercontent.com/226839/63507896-11f92a00-c4d9-11e9-9395-621355dec16b.png)

I've fixed this for you by modifying this to point to demo.api-test.nl and verified on staging:

https://1566469971164-vng-staging.maykin.nl/api/v2/schema/

**Comment by HenriKorver** [comment]
Thanks
