### ISSUE TITLE
As PO I want a documentation website for the API Test Platform

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#179]
such that users can find the information they need easily

**Toelichting**:
...

**Oplossingsrichting**:
Use the same tooling as in the ZGW-project for generating the website from github. In that case the Python code has to be moved to another github repository.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by alextreme** [comment]
The idea here is that we move the current codebase to a new github /VNG-Realisatie/api-testvoorziening-code

**Comment by alextreme** [comment]
Repository has been created:

https://github.com/VNG-Realisatie/api-testvoorziening-code

**Comment by HenriKorver** [comment]
Great! But are you already developing on this new repository?

**Comment by AlviseSembenico** [comment]
@HenriKorver yes, just started

**Comment by JanWillemKooi** [comment]
Needs more refinement to make clear what is needed

**Comment by AlviseSembenico** [comment]
@HenriKorver As documentation you mean the openapi.yaml file like this one: https://github.com/VNG-Realisatie/gemma-zaken/blob/master/api-specificatie/ztc/openapi.yaml ?

**Comment by HenriKorver** [comment]
Yes, but I mean documentation in a broader sense. Thus also tutorials, faq, issues, guides, etc. 
So the oas specification must be both accesible via the documentation website (https://github.com/VNG-Realisatie/api-testvoorziening/.../openapi.json) as via the testplatform url (https://vng-staging.maykin.nl/api/v1/schema/openapi.json). The latter is not working properly because it should return a json or a yaml file but not a ReDoc file. The Redoc file should only be returned when the url ends on "schema" (https://vng-staging.maykin.nl/api/v1/schema)

**Comment by HenriKorver** [comment]
> Naar aanleiding van de afstemming tussen Alex en Jan Willem stellen we vast dat deze user story meer refinement nodig heeft, omdat het nu nog te onduidelijk is om opgepakt te kunnen worden.

The most important step had alreay been made. The code of testplatform has been moved to a seperate github repository (https://github.com/VNG-Realisatie/api-testvoorziening-code). So now we can use the existing github repository (the one we are in now)  as a documentation website. It is not so user-friendly as the generated website of ZGW (https://ref.tst.vng.cloud/), but it will do for now. 
The only thing missing is a link from the testplatform website to this documentation repository (https://github.com/VNG-Realisatie/api-testvoorziening)

**Comment by AlviseSembenico** [comment]
Now it is a bit clearer, I added the json/yaml file generation in this comitt a1156abdcdf6c24c726793cc4a8f87b794953d32 and i will link the code repository in the documentation.
