### ISSUE TITLE
As a PO I want testscripts for validating the API of the Test Platform itself

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#180]
such that we can practise what we preach.

**Toelichting**:
...

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by stevenbal** [comment]
I have added a provider test scenario called `API test platform API tests' to vng-test.maykin.nl. Once the required changes are deployed to staging I will add this test scenario there as well

**Comment by stevenbal** [comment]
Now available on staging as well: https://vng-staging.maykin.nl/server/testscenario/9/

**Comment by alextreme** [comment]
Na check door Henri mag deze terug naar @stevenbal zodat dit overgezet kan worden van vng-staging naar api-test.nl

**Comment by alextreme** [comment]
Security bevinding: #264

**Comment by HenriKorver** [comment]
Als ik het script draai dan faalt het, zie https://vng-staging.maykin.nl/server/239369b9-250a-4a3b-99c5-fe3ee4b3fd78/

**Comment by alextreme** [comment]
Controleer even of je username/password klopt, bij mij werkt het:

https://vng-staging.maykin.nl/server/ccfd4f39-cc6a-4677-9e22-aa666ff4024c/

**Comment by alextreme** [comment]
Verder besproken met Henri (en bevestigd dat het werkt zoals verwacht, Henri had zijn wachtwoord onjuist ingevoerd).

Het zou wenselijk zijn om 'username' en 'password' voor deze test scenario te vervangen door 'token'.

**Comment by HenriKorver** [comment]
> Controleer even of je username/password klopt, bij mij werkt het:
> 
> https://vng-staging.maykin.nl/server/ccfd4f39-cc6a-4677-9e22-aa666ff4024c/

Ja oeps inderdaad verkeerde username/password. Het werkt nu wel

**Comment by stevenbal** [comment]
Ik heb de login en logout eruit gelaten en username en password veranderd voor token op staging https://vng-staging.maykin.nl/server/testscenario/9/
