### ISSUE TITLE
•	Als beheerder wil ik met 2 verschillende user accounts in hetzelfde browservenster tegelijkertijd in kunnen loggen

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/api-test-platform#197]
...zodat ik eenvoudig kan switchen tussen een account met beheerauthorisatie en een account met gebruikerauthorisatie.

**Toelichting**:
...

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by alextreme** [comment]
Ik weet niet of dit is wat je bedoelt, maar het is via de 'hijack' knop in de beheeromgeving mogelijk om tijdelijk een gebruikersaccount over te nemen:

![Screenshot_2019-06-03_17-17-23](https://user-images.githubusercontent.com/226839/58813205-8ed7de80-8623-11e9-9a5a-1a85a88a494f.png)

**Comment by melsk-r** [comment]
Nee, want dan kan ik niet eenvoudig switchen tussen mijn ene en mijn andere identiteit. Ze moeten beide tegelijkertijd te benaderen zijn.

**Comment by JanWillemKooi** [comment]
Dit kan al door gebruik te maken van private mode op je browser.
