### ISSUE TITLE
Als beheerder wil ik bij het toevoegen van een nieuwe sessie type ook in een duidelijke omschrijving voorzien.

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/api-test-platform#202]
...zodat duidelijk is wat de functie is van het sessie type.
Er moet dus ook een functioneel verhaaltje aan toegevoegd kunnen worden.

**Toelichting**:
...

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by HenriKorver** [comment]
In the admin (see below) we need an extra textfield for adding a description
![afbeelding](https://user-images.githubusercontent.com/37145898/59260592-32d11380-8c3c-11e9-944a-54ebdae2f473.png)

We also need a place to display this session type description  on the public website of the ATP.

Moreover we also need to add description fields to the scenario cases:

![afbeelding](https://user-images.githubusercontent.com/37145898/59262055-c99ecf80-8c3e-11e9-9588-fccb158c61fb.png)

**Comment by HenriKorver** [comment]
Dit is nu opgelost met info pages
