### ISSUE TITLE
As PO I want a tutorial for testing ZGW-API's and -consumers on the ATP

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#207]
such that users can get to work quickly

**Toelichting**:
The open question is how and where these tutorials are documented (github?)

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by alextreme** [comment]
Do this after #179

**Comment by AlviseSembenico** [comment]
The tutorials have been added in the following folder https://github.com/VNG-Realisatie/api-testvoorziening/tree/master/tutorials

**Comment by alextreme** [comment]
@AlviseSembenico please update the tutorials after doing #218. Unfortunately turning all the labels to English means the tutorials need to be redone (the screenshots are otherwise outdated).

The good news is that you don't have to understand Dutch anymore to follow the tutorial :)

**Comment by AlviseSembenico** [comment]
https://github.com/VNG-Realisatie/api-test-platform/commit/80de0997bff46d24abc908e7d2cebb12f80bc705

**Comment by alextreme** [comment]
Discussed today:

Although the tutorials are a good high-level overview, they don't not contain a concrete example against a specific API.

As such lets expand the current documentation with a concrete Demo API tutorial, showing both the consumer and the provider side.

**Comment by alextreme** [comment]
demo api is now available via demo.api-test.nl, issue has been unblocked

**Comment by alextreme** [comment]
@stevenbal graag nog even deze screenshot aanpassen:

https://raw.githubusercontent.com/VNG-Realisatie/api-testvoorziening/master/tutorials/images/providers_summary.png

**Comment by JanWillemKooi** [comment]
Foutje. Had deze niet moeten closen. Ben wel bezig geweest met Tutorial Consumer. Opmerkingen zijn als Pull Request ingeschoten.

**Comment by alextreme** [comment]
Besproken met Steven en Jan Willem, enkele opmerkingen die zijn doorgevoerd maar verder in orde.

Aan Henri ter controle.
