### ISSUE TITLE
As a user I want the example URL's, client-id and secret of the provider-testrun to be configurable in the admin interface

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#214]
**Toelichting**:
Now the example URL's are hard coded

![afbeelding](https://user-images.githubusercontent.com/37145898/60019726-daaffd80-968e-11e9-8626-198efcc628af.png)

But may be I want to change the urls into other more realistic URL's:

![afbeelding](https://user-images.githubusercontent.com/37145898/60019928-3aa6a400-968f-11e9-823f-1c92473f7bca.png)

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by AlviseSembenico** [comment]
https://github.com/VNG-Realisatie/api-test-platform-code/pull/23

**Comment by alextreme** [comment]
The placeholder URLs are now configurable per provider scenario:

https://vng-staging.maykin.nl/admin/servervalidation/testscenario/8/change/

We did notice an issue related to the ordering of the fields that we're investigating, but the functionality as requested has been implemented. 

I think it's a very good improvement, it takes a lot of URL guess-work out of creating a new provider run!

![Screenshot_2019-07-10_14-36-34](https://user-images.githubusercontent.com/226839/60969597-367db600-a320-11e9-8890-44ee49a5b341.png)

![Screenshot_2019-07-10_14-38-09](https://user-images.githubusercontent.com/226839/60969652-5ad99280-a320-11e9-8562-4eb2fa15aea3.png)

**Comment by HenriKorver** [comment]
The example url's are not active such that they cannot be copied or re-used. Please make them active...
