### ISSUE TITLE
In a session type I cannot change or delete the test file (postman collection)

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#215]
# Bug

![afbeelding](https://user-images.githubusercontent.com/37145898/60021153-ba357280-9691-11e9-9fb8-a5d99841c141.png)

**Comment by alextreme** [comment]
This is done on-purpose, as scenario cases are linked to the endpoint you're trying to remove.

**Comment by HenriKorver** [comment]
But I cannot replace the test file by a new one. So how do I do that?

**Comment by alextreme** [comment]
Replacing the Postman file seems to not be possible in your screenshot due to the long filenames used.

In this case you can switch to the 'VNG Endpoints' and replace the Postman file there:
https://vng-staging.maykin.nl/admin/testsession/vngendpoint/16/change/

![Screenshot_2019-06-24_15-27-22](https://user-images.githubusercontent.com/226839/60022686-96bff700-9694-11e9-8808-3314f1cb98b9.png)

**Comment by HenriKorver** [comment]
Thanks for this work-around. This enabled me to review user story #189. But is it still possible to fix the long filename bug? Because I find VNG Endpoint not the logical place to maintain the test files

**Comment by alextreme** [comment]
Yes naturally, although I'm not sure how to do this in the best way. Lets discuss this Thursday and keep this in todo.

**Comment by alextreme** [comment]
@AlviseSembenico see the following, this should work if you apply an admin-css override to change min-width from 215px to 515px for the dropzone class:

![Screenshot_2019-06-27_18-25-07](https://user-images.githubusercontent.com/226839/60283284-1c4bdd00-9909-11e9-8ba4-e30b1fdb8c69.png)

![Screenshot_2019-06-27_18-26-13](https://user-images.githubusercontent.com/226839/60283293-1f46cd80-9909-11e9-9299-e038ff0b48ce.png)

**Comment by AlviseSembenico** [comment]
https://github.com/VNG-Realisatie/api-test-platform-code/pull/20

**Comment by alextreme** [comment]
@AlviseSembenico I think we missed this change when switching repositories, the file which should contain the CSS override is not available on staging:

https://vng-staging.maykin.nl/atvstatic/css/admin.css

**Comment by alextreme** [comment]
This is now working as intended, there is now sufficient width for showing long filenames of the postman collection:

https://vng-staging.maykin.nl/admin/testsession/sessiontype/5/change/

![Screenshot_2019-07-11_15-13-03](https://user-images.githubusercontent.com/226839/61053982-e91c4a00-a3ee-11e9-9fb1-7c3c04727180.png)
