### ISSUE TITLE
Als developer/gemeente wil ik alle documentatie over de API Testvoorziening op ref.tst.vng.cloud (en/of opvolger) kunnen vinden.

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/api-test-platform#217]
...zodat ik alle informatie die ik nodig heb om met ZGW aan de gang te gaan bij elkaar heb staan.
Het zou kunnen dat deze informatie daar al ergens staat maar n dat geval is zij slechtte vinden en moet daar iets aan gedaan worden. Wat mij betreft moet de documentatie wel los van de documentatie over de ZGW API's komen te staan aangezien de API Testvoorziening niet alleen van toepassing is op ZGW API's.

**Toelichting**:
...

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by HenriKorver** [comment]
Het ATP wodt gedocumenteerd door middel van info-pages en een github-repository
