### ISSUE TITLE
As a user of the API Test Platform I'd like all labels to be English

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#218]
Henri would like to ensure all labels in the UI of the platform are English. Please ensure they are specified as translatable in case a Dutch translation is required.

**Comment by AlviseSembenico** [comment]
https://github.com/VNG-Realisatie/api-test-platform-code/pull/22

**Comment by alextreme** [comment]
Thanks, nearly there @AlviseSembenico 

- "Documenten" in the left-menu
- "Wachtwoord vergeten?" on the login screen
- "Verplicht. Maximaal 150 tekens." on the registration screen
- "Controleer de OpenAPI specificatie schema" on OpenAPI inspection view (and "OpenAPI Chec" instead of " OpenAPI Check" as a title).

@HenriKorver FYI Alvise has done this but also ensured that the platform is set up to deal with multi-lingual usage in the future, as users can toggle their language (for now this only affects the admin):

![Screenshot_2019-07-10_14-42-45](https://user-images.githubusercontent.com/226839/60970100-86a94800-a321-11e9-8acc-b6db71c46327.png)

**Comment by alextreme** [comment]
@AlviseSembenico also check the registration flow. I tried this out on api-test.nl and got a Dutch message on the confirmation page.
