### ISSUE TITLE
Change name API Testvoorziening to API Test Platform

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/api-test-platform#219]
So that it is more in line with the GUI which is in English as well.

DoD
GitHub:  change to api-test-platform (status: done)
Slack: vngrealisatie.slack.com channel #api-testvoorziening change to #api-test-platform (status: ongoing)
vngrealisatie.slack.com channel #atv-scrum-team change to #atp-scrum-team  (status: ongoing)

**Comment by HenriKorver** [comment]
@JanWillemKooi Could you do a quick/global scan to see if the name change has taken place?

**Comment by HenriKorver** [comment]
I zag net in Slack twee kanalen waar de naamsverandering nog niet heeft plaatstgevonden:
`api-testvoorziening` en `atv-scrum-team` binnen `VNG Realisatie`. Ik weet niet of dit makkelijk te veranderen is. Misschien even aan het beheerteam vragen (@michielverhoef, @melsk-r )

**Comment by JanWillemKooi** [comment]
Toevallig ben ik daar gisteren even mee bezig geweest. Heb vooral mijn eigen PC en mailboxen aangepast :-) Maar ik zal even kijken hoe de Slack kanalen omgekat moeten worden.

**Comment by JanWillemKooi** [comment]
Ik heb contact gehad met (@michielverhoef ) We weten hoe we de naam in Slack kunnen aanpassen maar hebben beide de rechten niet. Waarschijnlijk heeft Robert die rechten wel. Vanmiddag even bespreken.

**Comment by JanWillemKooi** [comment]
Gisteren zijn de 2 channels in Slack omgekat door Robert Melskens. En daarmee is dit item klaar
