### ISSUE TITLE
Als leverancier wil ik weten welke test batches beschikbaar zijn

### ISSUE THREAD

**Issue by basretera** [VNG-Realisatie/api-test-platform#221]
...zodat ik weet welke scenariotesten we moeten ondersteunen om compatibiliteit aan te tonen als ZGW API-provider.

**Toelichting**:
Tot op heden hebben we scenariotesten als ZDS-provider uitgevoerd op het StUF Test Platform (STP). Door deze testen succesvol af te ronden kon ik als leverancier via een rapport aantonen dat ik ZDS compatibel ben. Gemeenten hebben hier behoefte aan en vragen hier regelmatig om, o.a. via de Softwarecatalogus.

Als ik het goed heb begrepen is er voor de ZGW API's iets vergelijkbaars op komst. Het is echter niet inzichtelijk welke batches er aan komen en welke API's binnen deze batches opgenomen zijn. Als leverancier heb ik hier wel behoefte aan om bij de ontwikkeling van de ZGW API's deze ook direct vanuit onze eigen CI/CD te kunnen testen in de juiste volgorde/prioriteit. 

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by HenriKorver** [comment]
@basretera Momenteel wordt er binnen het ZGW project gewerkt aan testscripts om ZGW API providers te testen, zie https://github.com/VNG-Realisatie/gemma-postman-tests. Als die klaar zijn zullen ze asap geplaatst worden op het API Test Platform. 

@alextreme Kun jij Steven vragen wat de status is van deze scripts en of hij zich wil aanmelden voor deze repository?

**Comment by HenriKorver** [comment]
@basretera Als je Postman hebt geïnstalleerd kun je de bovengenoemde scripts ook al zelf runnen zonder API Test Platform. Het testplatform is vooral nuttig op het moment je testrapporten wilt publiceren in combinatie met badges. Dus je kunt sowieso aan de slag als deze ZGW testscripts klaar zijn.

@joeribekker Weet jij wat de status is van bovengenoemde scripts?

**Comment by joeribekker** [comment]
Status is "Work in progress".

Op dit moment dekken de test scenario's een groot deel van de APIs maar ontbreekt nog een stukje uitleg hoe je het allemaal zelf aan de praat krijgt.

Doordat we nog geen 1.0 hebben van alle APIs zijn er ook steeds breaking changes waar de test scenario's dan weer op aangepast moeten worden.

Doel is om de testscripts vlak na de 1.0 gereed te hebben.

Ik wil alleen nog graag een OAS spec validator @henrikorver

**Comment by HenriKorver** [comment]
>Ik wil alleen nog graag een OAS spec validator

Bedoel je een OAS validator die de API spec controleert op compliancy met NL API Strategie zoals voorgesteld in userstory #82?
Op het ogenblik valt er vooralsnog  niet veel te valideren omdat de design rules van de NL API Strategie gereduceerd zijn tot een [kleine kern](https://github.com/Geonovum/KP-APIs/blob/d6f54bf9d776be62a9fe035e97e3f2202d4728da/Werkgroep%20API%20strategie/Designrules.md).
Waarom deze vraag in de context van dit issue? Is daar een speciale reden voor?

**Comment by joeribekker** [comment]
Nee, ik bedoel een test die de OAS van de leverancier basaal vergelijkt met de standaard: attributen, query params, resources, etc

**Comment by HenriKorver** [comment]
Dan weet ik nog niet precies wat je bedoelt. Is dit een nieuwe user story die je wilt indienen?

**Comment by joeribekker** [comment]
Ja :)

**Comment by HenriKorver** [comment]
@basretera Als er compliancy tests beschikbaar zijn voor de ZGW API's dan zul je daar via de gebruikelijke kananalen van op de hoogte worden gebracht.
