### ISSUE TITLE
Hide the "OpenAPI inspection" feature until this functionality has reached a more mature level

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#223]
# Taak

At the moment the "OpenAPI inspection" feature only checks the version of the OAS specification. This is not mature enough when going public. So it would be better to disable / hide this functionality in the production version.

**Comment by alextreme** [comment]
Feel free to pick this up @AlviseSembenico , I agree for now it will only confuse people
