### ISSUE TITLE
Migrate domain name confirmation mails  from maykinmedia.nl to api-test.nl

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#224]

**Comment by alextreme** [comment]
As communicated this was done during the migration from the staging database to api-test.nl

**Comment by HenriKorver** [comment]
Can I close this issue now?

**Comment by alextreme** [comment]
I think so, however note that this was updated only for the production environment on api-test.nl.

If this issue is instead about updating the sender of the test/staging environments (see also #225), then not.

**Comment by HenriKorver** [comment]
Clear! Than I keep this issue open because I want the domain names to be consistend across the test, staging and production environments

**Comment by stevenbal** [comment]
Deze verandering is inmiddels ook doorgevoerd op staging

**Comment by HenriKorver** [comment]
Als ik een wachtwoord wil wijzigen op staging om de confirmatie-mails te kunnen testen krijg ik een 500 melding:

![afbeelding](https://user-images.githubusercontent.com/37145898/65067512-fc1b3f80-d986-11e9-8b6e-1bf6509e43c5.png)

**Comment by alextreme** [comment]
Bij deze de error, het is een bug Steven pakt het morgen op:

https://sentry.maykinmedia.nl/maykin-media/vng-testplatform-staging/issues/260544/

**Comment by stevenbal** [comment]
@HenriKorver 

Had per ongeluk een breakpoint laten staan, ik heb het gefixed en gedeployed op staging.
