### ISSUE TITLE
Migrate test and staging environment from maykin.nl  to api-test.nl

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#225]

**Comment by stevenbal** [comment]
Zowel test als staging staan nu onder *.api-test.nl

Ook staan wordt er van de oude url geredirect naar de nieuwe:
https://staging.api-test.nl/server/a0c7217c-b47f-4800-92a3-3c3e7088fff4/
https://vng-staging.maykin.nl/server/a0c7217c-b47f-4800-92a3-3c3e7088fff4/

**Comment by HenriKorver** [comment]
Thanks!
