### ISSUE TITLE
Improve dashboard

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#226]
# Taak

Dashboard:

- height should be consistent
- link each block to the list-view of either consumer or provider

**Comment by alextreme** [comment]
@AlviseSembenico feel free to pick this up, seems I dragged it into in progress by accident

**Comment by AlviseSembenico** [comment]
@alextreme It has already been implemented and deployed.

**Comment by HenriKorver** [comment]
The boxes are now aligned correctly but the number are not correct

![afbeelding](https://user-images.githubusercontent.com/37145898/61462621-32cade80-a973-11e9-949b-60f4a24663fe.png)

For instance the first blue image should depict 5 scheduled provider runs. There are more wrong numbers in the other images if you take a closer look

**Comment by AlviseSembenico** [comment]
i fixed the blue image but i cannot see other error, the third one refers to the active sessions with docker so they must be active.

**Comment by HenriKorver** [comment]
I miss the dash-bord images for the non-scheduled provider tests and the one for the consumer sessions that are non-kubernetes
