### ISSUE TITLE
Ability to activate/deactivate Session Types and Test Scenario's

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#227]
# Taak

Please add an 'is_active' boolean for the Session Type and Test Scenario's. This should affect which of these objects are shown to the user when creating a new session or server run.

**Comment by HenriKorver** [comment]
Yes it works, but it the user interface to activate/deactivate is a bit cumbersome. I rather would be able to activate/deactivate more sessions types at once. For instance in the screen below I would like the radiobuttons on the right to be writable. Or it can also be done with the checkboxes on the left with an appropriate action: 

![afbeelding](https://user-images.githubusercontent.com/37145898/61547040-db983d00-aa4a-11e9-9103-70d98fa1a53b.png)

**Comment by alextreme** [comment]
Created new task #251 based on Henri's comment.
