### ISSUE TITLE
Consumer testing: Introducing of Scenario Case Collections to avoid duplicate cases

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#228]
Currently it is required to add a scenario case via the admin for each session type, and depending on how an API is used there can be multiple session types (for instance a Docker and a hosted API, or a session type per process (MOR, Vergunningen, Verhuizingen).

As such it would be useful to have 'scenario case collections'. These collections can then be reused across multiple session types, and we wouldn't have to re-enter the scenario cases in these situations.

**Comment by alextreme** [comment]
Dit is inmiddels via een andere user story beschikbaar op vng-staging

**Comment by stevenbal** [comment]
closed in favor of https://github.com/VNG-Realisatie/api-test-platform/issues/206
