### ISSUE TITLE
Als beheerder wil ik alle configuratie van leveranciers en gemeenten kunnen zien en wijzigen

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-test-platform#23]
zodat ik bij een vraag van de tester kan zien wat er gebeurd is, de tester verder kan helpen en het probleem zo nodig (laten) oplossen.

Testers kunnen vragen stellen aan de beheerder zoals:
- waarom krijg ik een foutmelding?
- waarom krijg ik geen antwoord?
- enz.

**Toelichting:**
De oorzaak van dit soort vragen kan soms liggen aan de configuratie die door de tester is gemaakt. De beheerder moet dit soort vragen kunnen beantwoorden door te analyseren wat er is gebeurd en wat de huidige toestand is.

**Oplossingsrichting**:
Relevante configurarei is:
- de configuratie van endpoints van de te testen applicatie (m.n. wanneer de te testen applicatie provider is van de api)
- de endpoints die beschikbaar zijn in de testvoorziening voor de testorganisatie/applicatie (waar moet de client requests naartoe sturen)
- autorisatie-configuratie, bijvoorbeeld de api-key

Dit moet voor de beheerder raadpleegbaar zijn via een gebruikersinterface (webpagina). Deze moet alleen toegankelijk zijn met beheerdersrechten.
De beheerder moet het probleem ook kunnen oplossen door de configuratie van de tester (testorganisatie) te kunnen wijzigen.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Prototype (indien niet van toepassing afvinken)
- [ ] Funcitionele specificatie
- [ ] Technische specificatie
- [ ] Non functionals (eisen/specificatie)
- [ ] Documentatie bijgewerkt

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
- [ ] ...
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by HenriKorver** [comment]
Met de hijack mogelijkheid kan de beheerder meekijken met de testsessies
