### ISSUE TITLE
Provider test scenario - improve description page

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#231]
# Taak

https://vng-staging.maykin.nl/server/testscenario/8/

Henri would like to have a link from this page (as a button) to the Postman collection that will be run.

Also show the various URL-variables that need to be set and the placeholders for the Test scenario.

Also see if you can inspect the PM collection to show (in advance) which requests/tasks/assertions are taking place.

**Comment by alextreme** [comment]
@AlviseSembenico @HenriKorver ran into an error which seems to be dependent on parsing the Postman collection requests. Sentry has further details, I suspect it has to do with different ways how a PM collection can be formatted.

https://sentry.maykinmedia.nl/maykin-media/vng-testplatform/issues/257734/

As you've added quite a bit of collection-dependent logic to the inspections templatetags and various filters, ensure you provide good fallbacks in case your PM-inspection fails (which it will, it's a complex format). Filters and templatetags shouldn't cause errors if their input is different than expected.

I've reverted your change on master as it shouldn't have gone through to (pre)production yet.

Lets get this working properly with the scenario's on test first (and add these to our test-suite to verify this keeps working), I don't think Henri has a need to rush the PM-inspection through before live.

(and also note that the second item, "Also show the various URL-variables that need to be set and the placeholders for the Test scenario.", still needs to be done too)

**Comment by AlviseSembenico** [comment]
This problem is due to nested folders in the postman collection, I am unwrapping all the calls and making sure that the filters do not raise any error

**Comment by alextreme** [comment]
Thanks, this is working for me now on staging:

https://vng-staging.maykin.nl/server/testscenario/8/

**Comment by alextreme** [comment]
Scrolling down it would be good to improve how this is shown for code snippets (due to the keeping of formatting they flow outside the container), but I suspect give Henri's earlier remarks this week that he would also like other improvements made, so I'd like his input.

**Comment by HenriKorver** [comment]
I will come back on the oter improvements next Thusday

**Comment by HenriKorver** [comment]
Something else: the blue download button suggests that it is also possibe to download the postman collection directly. Now one is forwarded to a webpage where the postman collection is shown in the browser. Of course it can be copied or downloaded from there.

![afbeelding](https://user-images.githubusercontent.com/37145898/61545144-0ed8cd00-aa47-11e9-9918-a58321c0bc6c.png)

**Comment by HenriKorver** [comment]
@alextreme @stevenbal Postman allows to publish collections to a public website, for instance:
https://documenter.getpostman.com/view/1681967/SVSPo7S3?version=latest

![afbeelding](https://user-images.githubusercontent.com/37145898/61699208-bbae9500-ad3a-11e9-9a9a-cca8c31c1ba8.png)

This really looks nice and it would be a great additional feature to our description pages. The question is whether we can automate this via Newman?

There is one drawback: the website does not show the assertions (Java testcripts). On the other hand it gives you the possibility to switch to Postman directly. There you can see the assertions.

**Comment by HenriKorver** [comment]
Improvements for the screen shot below: provide the code snippits with a scroll bar such that more space is created for the first two columns. The columns `Name space` and `Url` are now very crammed up.

![image](https://user-images.githubusercontent.com/37145898/61793803-208feb00-ae20-11e9-8963-bbd83e7975f4.png)

**Comment by alextreme** [comment]
Summarizing our discussion: Henri would like us to tackle the following two requests within this story:

https://github.com/VNG-Realisatie/api-test-platform/issues/231#issuecomment-514615390

https://github.com/VNG-Realisatie/api-test-platform/issues/231#issuecomment-513266389

The getpostman.com request is delegated #252

**Comment by alextreme** [comment]
https://vng-staging.maykin.nl/server/testscenario/5/

Verified that the two requests (not #252) have been done:

![Screenshot_2019-08-08_16-01-03](https://user-images.githubusercontent.com/226839/62709525-d6009800-b9f5-11e9-8b22-4e1f50a89ef9.png)
