### ISSUE TITLE
Review security issues api-test-platform-code

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#232]
# Taak

Ensure we've got updated requirements before going live with api-test.nl:

https://github.com/VNG-Realisatie/api-test-platform-code/network/alerts

**Comment by AlviseSembenico** [comment]
I get a 404 from the link, probably because i don't have enough rights.

**Comment by HenriKorver** [comment]
@AlviseSembenico I just gave you admin rights. Does this help?

**Comment by AlviseSembenico** [comment]
yes, it is fine now

**Comment by alextreme** [comment]
This works for me, thanks Alvise!

![Screenshot_2019-07-18_14-52-31](https://user-images.githubusercontent.com/226839/61458837-bb458100-a96b-11e9-9bec-a435438e348f.png)
