### ISSUE TITLE
Consumer detail-view: ensure Report-links work for unauthenticated users

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#235]
# Taak

Discovered together with @HenriKorver 

When checking a consumer detail-view we noticed that the report-buttons didn't work (403). 

The report and report-pdf links should be accessible by unauthenticated users as well:

https://vng-staging.maykin.nl/fe8a55f6-669c-49c0-a963-2798a76cd0fd/

![Screenshot_2019-07-11_17-25-27](https://user-images.githubusercontent.com/226839/61063823-eb879f80-a400-11e9-97bc-66eec01c11aa.png)

**Comment by AlviseSembenico** [comment]
https://github.com/VNG-Realisatie/api-test-platform-code/pull/53
