### ISSUE TITLE
Problem with badges (custum badge is inaccessible)

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#239]
# Bug

See for instance https://api-test.nl/server/da1ee20b-f17e-4db2-b0af-675d6132cd28/

![afbeelding](https://user-images.githubusercontent.com/37145898/61132206-2e0db280-a4bb-11e9-8850-257441950de8.png)

Please fix this before the demo!

**Comment by alextreme** [comment]
I've had a look, the API returns the correct results and the Shields.io endpoint works in the browser but there's a SSL certificate error when doing this from the commandline. I suspect the intermediate certificate ordering is incorrect, Qualys should provide further details.

**Comment by HenriKorver** [comment]
Did you already send a request to Qualys for clarification?

**Comment by alextreme** [comment]
I've fixed the issue, seems I missed a certificate in the SSL chain when copying over the api-test.nl certificate to the production server:

![Screenshot_2019-07-12_16-49-58](https://user-images.githubusercontent.com/226839/61137161-50a4c900-a4c5-11e9-9ec3-531a820d5f07.png)

![Screenshot_2019-07-12_16-51-52](https://user-images.githubusercontent.com/226839/61137193-5c908b00-a4c5-11e9-86ca-2abc91d6416c.png)

**Comment by HenriKorver** [comment]
Nice, now it looks much better ;-)
