### ISSUE TITLE
Als beheerder wil ik alle testvoortgang van leveranciers en gemeenten kunnen zien

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-test-platform#24]
zodat ik bij een vraag van de tester kan zien wat er gebeurd is, de tester verder kan helpen en het probleem zo nodig (laten) oplossen.

Testers kunnen vragen stellen aan de beheerder zoals:
- waarom krijg ik een foutmelding?
- waarom krijg ik geen antwoord?
- waarom valideert mijn api call niet?
- waarom is mijn test niet geslaagd?
- waarom zegt het rapport dat de test niet is afgerond?
- enz.

**Toelichting**:
De beheerder moet dit soort vragen kunnen beantwoorden door te analyseren wat er is gebeurd en wat de huidige toestand is.
Hiertoe moet deze kunnen zien:
- per teststap wat de status is
- welke requests gedaan zijn, bij welke teststap die "geland" zijn, welke response erop gekomen is

**Oplossingsrichting**:
- De beheerder raadpleegt dit via een gebruikersinterface (webpagina). 
- Deze is alleen toegankelijk met beheerdersrechten.

Er zijn twee ingangen/overzichten die hiervoor nodig zijn:
1. tester (testorganisatie) > applicatie > testuitvoering
    Dit toont de uitvoering van het scenario, dus alle geconfigureerde teststappen. Van elke teststap wordt de hele configuratie getoond (bijv. welke validaties gedaan worden), de status van de teststap (zoiets als: niet uitgevoerd;wacht op client;succes;gefaald), requests en responses.
2. bericht logging
    Op timestamp gesorteerd (aflopend) overzicht van alle requests en bijbehorende responses. Dit overzicht moet te filteren zijn op zender(uri), ontvanger(uri),periode(timestamp). We moeten er in gebruik achter komen wat er precies nodig is aan filtering. Details van een request-response interactie moet alle details tonen (o.a. bericht body), en wanneer van toepassing ook de testorganisatie, applicatie, testuitvoering/scenario en teststap waaraan deze is gerelateerd.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Prototype (indien niet van toepassing afvinken)
- [ ] Funcitionele specificatie
- [ ] Technische specificatie
- [ ] Non functionals (eisen/specificatie)
- [ ] Documentatie bijgewerkt

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
- [ ] ...
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by HenriKorver** [comment]
Beheerders kunnen de testvoortgang volgen via de hijack functionaliteit
