### ISSUE TITLE
ATP should be able to generate JWT tokens dynamically in case they have a short term expiration date

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#240]
On the production website (https://api-test.nl/server/6/create/) one finds the fields Client-id and secret:

![afbeelding](https://user-images.githubusercontent.com/37145898/61133074-fdc71380-a4bc-11e9-8172-818b9bee1fe3.png)

But these two fields are not visible in de admin section and can not be configured with an example. Probably these fields are generated. What is the use of these generated fields?

**Comment by alextreme** [comment]
The Client ID and Secret fields are automatically added and required if authorization is set to JWT.

**Comment by HenriKorver** [comment]
I do not understand why Client ID and Secret are required. Supplying a JWT token should be enough in this case. Client ID and Secret are only needed when you want to generate a new JWT dynamically. But that is not what is happening here. The ATP just accepts the JWT token entered by the user and does not generate one by itself.

**Comment by alextreme** [comment]
If you are using 'JWT' as a variable to perform the authentication manually in your postman collection, then you can simply turn authentication off ('no auth') in the scenario.

If you select 'JWT' as authentication mechanism for your provider scenario, then a JWT token is generated on-the-fly using the Client ID and Secret entered by the user and applied to the postman collection calls performed. This is as Alvise explained it yesterday.

JWT tokens can (should?) expire so for setting up a scheduled test APIs where this is the case you can provide your long-lived Client ID and Secret and have api-test generate the token for you.

**Comment by HenriKorver** [comment]
Thanks for this clarification, then I will switch authentication off to proceed. However with authentication on api-test does not generate a proper token for me: see this provider run:
https://api-test.nl/server/35b49df7-eaea-4abc-bf6e-9ec8a1767225/

**Comment by AlviseSembenico** [comment]
It is because of the changes in the ref version, with the drop of wildcard permission. I will fix it

**Comment by alextreme** [comment]
I'll drag this into the sprint, just in case so we'll verify the token generation on production

**Comment by AlviseSembenico** [comment]
@HenriKorver, before the changes the test platform was able to claim all the possible authorization but it has been changed and now the auths are fetched from the Authorization Component.

**Comment by alextreme** [comment]
@AlviseSembenico could you double-check that a valid Client ID and Secret work as expected on production? After this Henri can review and close.

**Comment by AlviseSembenico** [comment]
I checked it yesterday with Sergei and and eventual lack of permission must be fixed through the AC component
