### ISSUE TITLE
Provider postman run: Incorrect HTML-log output?

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#241]
# Bug

Raised by @HenriKorver 

I've started a Demo API run and this succeeds and all calls are green:

https://vng-staging.maykin.nl/server/ed9664ef-bec9-4e08-af3c-cae60599f815/

However when checking the HTML output it shows that requests have failed:

https://vng-staging.maykin.nl/server/ed9664ef-bec9-4e08-af3c-cae60599f815/log/

This was done using the following URL: https://ref.tst.vng.cloud/demo-api/api/v2

I'm not sure which of the two is correct. Perhaps something has changed in how we call newman?

**Comment by HenriKorver** [comment]
I want to show the HTML output in the demo coming Thursday. So it would be nice if this could be fixed no later than tomorrow, but even better today

**Comment by AlviseSembenico** [comment]
Problem is addressed here https://github.com/VNG-Realisatie/api-test-platform-code/pull/59

**Comment by HenriKorver** [comment]
Where can I see the fix? Test server (https://vng-test.maykin.nl) gives 401 Authorization Required

**Comment by AlviseSembenico** [comment]
I am upgrading stage right now

**Comment by AlviseSembenico** [comment]
It is now updated, You have to rerun the test though

**Comment by AlviseSembenico** [comment]
Moved to textfield
![image](https://user-images.githubusercontent.com/28757412/61375990-799bd400-a8a0-11e9-83f1-e5ea012032f2.png)

**Comment by HenriKorver** [comment]
I get this error:

![afbeelding](https://user-images.githubusercontent.com/37145898/61377109-d7c9b680-a8a2-11e9-81b3-e4a2201ce279.png)

**Comment by AlviseSembenico** [comment]
The current update should fix the problme

**Comment by HenriKorver** [comment]
Where can I test the fix?

**Comment by AlviseSembenico** [comment]
It is now released on staging, https://vng-staging.maykin.nl/server/80dfa5d9-4309-459b-b609-a48704352bce/ here the example

**Comment by HenriKorver** [comment]
Super cool!!!!! Will this also be rolled out to the production server (api-test.nl)?

**Comment by AlviseSembenico** [comment]
Sure Henri! I will be deployed on api-test as well

**Comment by HenriKorver** [comment]
Today? So I can show it tomorrow on the production version

**Comment by AlviseSembenico** [comment]
It has been already deployed.

**Comment by alextreme** [comment]
Currently verifying this on production after doing the deploy.

I do get errors from the ZGW & Demo APIs, but the newman reports are being generated again and the two outputs (JSON and HTML) are more in line with each other.

**Comment by HenriKorver** [comment]
It worked during the live demo and thus  I was very happy
