### ISSUE TITLE
Consumer sessions: Ensure production / api-test.nl uses correct subdomains

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#242]
# Taak

Investigated the DNS/subdomain issue, and the DNS entries in Hostnet are correct.

However api-test.nl currently uses:

https://1563187861114-api-test.nl

While it should use subdomains under api-test.nl:

https://1563187861114.api-test.nl

I couldn't figure this out easily myself, so assigning to Alvise to resolve this.

**Comment by HenriKorver** [comment]
I gave you login acces to hostnet via mail. Can I close this issue?

**Comment by HenriKorver** [comment]
Can I close?

**Comment by alextreme** [comment]
No Henri, don't close. I've edited the issue accordingly and we'll investigate further on Wednesday.

**Comment by AlviseSembenico** [comment]
https://github.com/VNG-Realisatie/api-test-platform-code/commit/93f8c4a58ca1551fccd36b5f304c4d1984f4a621

**Comment by alextreme** [comment]
Now working as intended. I'll close.
