### ISSUE TITLE
Placeholer fields are not big enough to contain jwt tokens

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#244]
# Bug

![afbeelding](https://user-images.githubusercontent.com/37145898/61282032-ef2d7480-a7ba-11e9-96d5-2c24c7dc3113.png)

Please fix this before the demo

**Comment by AlviseSembenico** [comment]
Moved to textview
![image](https://user-images.githubusercontent.com/28757412/61376018-89b3b380-a8a0-11e9-9459-35441b61fa39.png)

**Comment by HenriKorver** [comment]
Thanks
