### ISSUE TITLE
Url's test.api-test.nl and staging.api-test.nl are not properly redirected

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#245]
# Bug
These wrong links are redirected correctly:

https://vng-test.api-test.nl
https://vng-staging.api-test.nl

However these good links not;

https://test.api-test.nl
https://staging.api-test.nl

**Comment by HenriKorver** [comment]
Maybe we should also change https://test.api-test.nl into https://testing.api-test.nl
This would be more coherent with https://staging.api-test.nl

**Comment by alextreme** [comment]
This is on the backlog, see: #225 

I'm not sure why this is added and why this would be a bug, we discussed last week that #225 wouldn't be required this week.

**Comment by HenriKorver** [comment]
You said yesterday that I should work on the staging version for preparing the demo. So I am now forced to use the url https://vng-staging.api-test.nl which is in my opinion not the right url. It should be https://staging.api-test.nl

It is no big deal but I find it a very ugly url especially for demo purposes

**Comment by HenriKorver** [comment]
But indeed let's focus on the other issues now because there are more important ones to solve

**Comment by stevenbal** [comment]
dit is doorgevoerd door https://github.com/VNG-Realisatie/api-test-platform/issues/225
