### ISSUE TITLE
How can I add links in the info pages?

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#246]
Putting in a HTML-link directly as done below does not work:

![afbeelding](https://user-images.githubusercontent.com/37145898/61372521-a13a6e80-a897-11e9-9bff-ec51594b6175.png)

**Comment by AlviseSembenico** [comment]
You can use the chain icon that is selectable when you select some text.

**Comment by HenriKorver** [comment]
Ooh great thanks, it works now
