### ISSUE TITLE
How can I insert images on the info pages?

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#247]
This form does not help a lot:

![afbeelding](https://user-images.githubusercontent.com/37145898/61373291-b3b5a780-a899-11e9-8373-b14c7315edaf.png)

I just want to upload a picture from my computer by using the explorer

**Comment by AlviseSembenico** [comment]
Sorry Henri, I strugge to understand which page are you referring to.

**Comment by HenriKorver** [comment]
It comes up when you press this button:

![afbeelding](https://user-images.githubusercontent.com/37145898/61375120-5cfe9c80-a89e-11e9-94a9-39a5a37f3f0e.png)

**Comment by alextreme** [comment]
As far as I know we only discussed basic formatting and links, not adding images to the test scenario description pages. The WYSIWYG-options added are the defaults for this editor.

You can add images using the shown option, however you would have to place a URL to an image you uploaded in Filer (or somewhere else), it's not very user-friendly.

**Comment by HenriKorver** [comment]
Thanks for the tips. It is working OK for know.
