### ISSUE TITLE
Sentry error - PUT on demo-api

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#249]
# Taak

I'm not sure if PUT is an operation that works on the demo-api, however either way good to investigate:

https://sentry.maykinmedia.nl/maykin-media/vng-testplatform/issues/257866/

**Comment by AlviseSembenico** [comment]
The behaviour is as expected, probably sentry considers is an error since the result of the call is a 500

**Comment by alextreme** [comment]
Okay, this works for me.
