### ISSUE TITLE
6 december 1 samenwerkingsdag organiseren

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-test-platform#25]

**Comment by TCIMEddy** [comment]
@joeribekker Alex is nog geen lid van deze groep dus maar even op jou naam gezet.

**Comment by joeribekker** [comment]
Bij deze Alex toegevoegd als collaborator. @michielverhoef moet Alex even toevoegen aan een team.

**Comment by michielverhoef** [comment]
Ik heb Alex net toegevoegd aan het "write" team, met dezelfde rechten als een collaborator. Mocht hij meer willen dan hoor ik dat wel :-)

**Comment by alextreme** [comment]
Merci!
