### ISSUE TITLE
Increase the size of the description-control such that one has more space and overview while editing

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#250]
# Taak

![afbeelding](https://user-images.githubusercontent.com/37145898/61465797-116cf100-a979-11e9-8496-adf26939b7ac.png)

**Comment by AlviseSembenico** [comment]
Does this dimension work for you?
![image](https://user-images.githubusercontent.com/28757412/61522595-f353cf00-aa12-11e9-8cea-5a06ea2eb321.png)

**Comment by HenriKorver** [comment]
Looks allright. It would be nicer of course if I can adjust the dimension of the control myself by dragging the borders. But I do not know if this is possible.

**Comment by AlviseSembenico** [comment]
Yes, it is possible, just implemented, https://github.com/VNG-Realisatie/api-test-platform-code/pull/71.

**Comment by HenriKorver** [comment]
Can I already review it?

**Comment by alextreme** [comment]
Feel free to verify on staging:

https://vng-staging.maykin.nl/admin/testsession/sessiontype/6/change/

![Screenshot_2019-07-25_17-25-39](https://user-images.githubusercontent.com/226839/61887103-417c3d00-af01-11e9-93ed-be8df656361e.png)
