### ISSUE TITLE
Add link to the published version of the Postman collection on the detail page of the provider run

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#252]
# Taak

For instance add this link to the the detail page of the provider run "ZGW-provider test voor Melding Openbare Ruimte":

https://documenter.getpostman.com/view/1681967/SVSPo7S3?version=latest

![afbeelding](https://user-images.githubusercontent.com/37145898/61699208-bbae9500-ad3a-11e9-9a9a-cca8c31c1ba8.png)

The challenge is to generate this documention website with the appropriate environment variables such that you can run it directly in Postman.

![afbeelding](https://user-images.githubusercontent.com/37145898/61701941-3d082680-ad3f-11e9-94f5-17042ff8b1c4.png)

See also #231

**Comment by HenriKorver** [comment]
If we have the Pro version of Postman the pages can also be published within the domain of api-test.nl.

![afbeelding](https://user-images.githubusercontent.com/37145898/61712132-e823da80-ad55-11e9-994d-bd08cf15a1c7.png)

**Comment by HenriKorver** [comment]
The question is whether we can use this functionality via the command-line API of Newman.

**Comment by HenriKorver** [comment]
The same link must be added to the corresponding info-page

**Comment by alextreme** [comment]
Een link naar getpostman kan nu geplaatst worden, maar hoe dit wordt weergegeven is niet helemaal logisch.

Ik zou verwachten dat in plaats van 'Info' dat er zou staan 'Published Postman collection' of iets dergelijks, zodat het duidelijk is waar ik naar toe ga.

**Comment by alextreme** [comment]
Link naar bijbehorende environment variabelen toevoegen

**Comment by stevenbal** [comment]
> Link naar bijbehorende environment variabelen toevoegen

Ik heb even gekeken of dit kan, maar links naar environment variablen zijn alleen toegankelijk voor mensen die bij Postman in dezelfde workspace zitten, dus die kun je niet individueel publiceren. Wel kun je bij het publiceren van een collectie aangeven welke environment variabelen erbij horen, en die zijn dan zichtbaar op de pagina van de gepubliceerde collection
