### ISSUE TITLE
As PO I want a stable demo-api

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#253]
such that:
* developers have an essential starting point to base their coding on 
* documenters have an example to base their tutorials on 
* new users can use it as an example case
* presenters can use it in their demonstrations

**Toelichting**:
Up to now we have used the demo-api (also known as the Quote API): https://zaakgerichtwerken.vng.cloud/demo-api/api/v2/
However at the moment this api is down because it has not been moved to the new Haven cluster and nobody feels responsible for maintaining it.

The code of the demo-api is hosted here: https://github.com/maykinmedia/demo-api-component

**Oplossingsrichting**:
Move the demo-api to Haven and make the ATP-team owner of this application.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by HenriKorver** [comment]
@melsk-r @michielverhoef The demo-api has been developed by  @joeribekker for API Beheer as an example to demonstrate the basics of mainting an API. Are you still using it?

**Comment by alextreme** [comment]
@HenriKorver The demo-api is available as a docker container, so in principe @kciredor should be able set this up for you on Haven: https://hub.docker.com/r/maykinmedia/vng-demo-api

We can set up the DNS for demo.api-test.nl to point to Haven tomorrow.

**Comment by kciredor** [comment]
Just to make sure we're on the same page :-) Haven is not DevOps-as-a-service, it's more about Kubernetes-as-a-Service.

I can provision a namespace on Haven and hand out credentials to the person or team that will be setting up and maintaining this. Who will that be?

**Comment by HenriKorver** [comment]
Up till now @joeribekker was the developer/ owner of the demo-api. However it seems that he is not wanting to maintain this api any more. However the ATP is dependent on this demo-api. So the question is whether the programmers of the ATP-team (@alextreme or @stevenbal ) can take it over...

**Comment by alextreme** [comment]
In that case the Devops team responsible for Haven should take this over, in my eyes. If you want us to do maintenance it won't run on Haven, as we only maintain installs on our own infrastructure.

**Comment by kciredor** [comment]
This feels like walking in circles.

**Comment by joeribekker** [comment]
The demo-api was created for API-beheer, to show them how API versioning, changelogs, etc. works. And, to play around with an easy to use, actual API. It was then used by the API-testplatform to test API's.

@HenriKorver I think the ATP project needs to take over this project if you guys rely on it. I can move this to somewhere on Haven and make it available but will be on ATP hours.

**Comment by joeribekker** [comment]
DevOps as a service is wel nog echt een gebrek in het Haven team :)

**Comment by kciredor** [comment]
Ik weet dat jij er zo over denkt :-)

Haven gaat over standaardisering van gemeentelijke infrastructuur. Intern zijn we begonnen met uitrollen van de beoogde infra, waardoor we ervaring op kunnen doen tijdens de ontwikkeling ervan.

Dat is iets fundamenteel anders dan DevOps outsourcing.

Als blijkt dat er behoefte is aan interne DevOps as a service, zal er zodoende een nieuw initiatief moeten ontstaan om daar invulling aan te geven.

**Comment by JanWillemKooi** [comment]
Laten we de discussie DevOps-as-a-service niet via deze US doen. Terug naar het onderwerp: Hoe krijgen we voor ATP een beheerde demo-applicatie. We kunnen het, zoals @joeribekker voorstelt, in het project opnemen, echter het beheer van ATP zal (stapgewijs) overgaan naar VNG API-Beheer (lees: Michiel en Robert). Dat lijkt me ook de juiste manier. Eens? 
De vervolg vragen zijn: Is API-Beheer hiertoe bereid en in staat? En is de Demo-API genoeg ontwikkeld om beheerd te kunnen worden. Met andere woorden: voldoen het aan de intake criteria van API-Beheer?

**Comment by joeribekker** [comment]
Als de scope zo was als je omschrijft:

> Haven gaat over standaardisering van gemeentelijke infrastructuur. 

Dan vergeet je dat toch echt dat er nu dus APIs in productie zijn op het Haven platform van VNG. Dat is meer en iets anders dan alleen "ervaring opdoen".

Ik zeg niet dat jij moet devopsen erbij (het is niet persoonlijk bedoeld) maar ik vind dat VNG er tijd voor moet vrijmaken (binnen de API teams zelf of anders, zoals devops overkoepelend).

**Comment by joeribekker** [comment]
Excuus @JanWillemKooi. Zag je commentaar te laat.

**Comment by JanWillemKooi** [comment]
Demo werkt nu niet. Om dit op te lossen:
1ste Redirect
2de hosten op huidige productie omgeving

**Comment by alextreme** [comment]
Installatie is uitgevoerd op een van onze productieservers. De demo-api is weer te benaderen, nu via: demo.api-test.nl

![Screenshot_2019-08-01_18-44-12](https://user-images.githubusercontent.com/226839/62312377-4f483a00-b48e-11e9-88be-090163c05456.png)

**Comment by HenriKorver** [comment]
The badge on the github repository of the demo-api does not work: https://github.com/maykinmedia/demo-api-component

Moreover, this repository should be moved to the vng domain.

**Comment by alextreme** [comment]
Both requests are separate issues/tasks in my eyes, I suggest to slice this story

**Comment by HenriKorver** [comment]
Could you slice it for me?

**Comment by alextreme** [comment]
@melsk-r graag hebben we een fork van https://github.com/maykinmedia/demo-api-component onder https://github.com/VNG-Realisatie waarbij Henri beheer-rechten heeft

**Comment by michielverhoef** [comment]
@alextreme: check https://github.com/VNG-Realisatie/demo-api-component

**Comment by stevenbal** [comment]
Ik heb het test scenario voor de demo API wat uitgebreid (https://api-test.nl/server/testscenario/9/) en heb een PR gemaakt om de test scenario badge op de readme te zetten @alextreme  (https://github.com/maykinmedia/demo-api-component/pull/5)

**Comment by HenriKorver** [comment]
Ik zie dat de badges nog steeds in beta zijn. Moeten we dat niet opheffen nu we richting live-gang gaan?

**Comment by alextreme** [comment]
@HenriKorver ik dacht dat jij (beta) juist in de badge er in wou houden, in het kader van permanent beta. Maar als je het weg wilt hebben dan halen we het weg.

**Comment by HenriKorver** [comment]
Dan ben ik van mening veranderd, haal het maar weg.

**Comment by alextreme** [comment]
Bij deze op staging:

![Screenshot_2019-10-10_14-00-40](https://user-images.githubusercontent.com/226839/66566902-611d1c00-eb66-11e9-82de-ace039a6206f.png)

**Comment by HenriKorver** [comment]
De readme van de github repository van de demo-api is nog een rommeltje en de badge die daar staat werkt niet. 
https://github.com/VNG-Realisatie/demo-api-component

**Comment by alextreme** [comment]
Bij deze even opgeschoond en de badge vervangen, de scheduled run was er zo te zien een waarbij we alle environments van hadden gewist:

![Screenshot_2019-10-14_14-13-30](https://user-images.githubusercontent.com/226839/66750456-d05b7e80-ee8c-11e9-9df1-cd33343faba2.png)

**Comment by HenriKorver** [comment]
Als ik klik op de badge krijg ik niet het gewenste resultaat. Bovendien zijn diverse kopjes zoals Inleiding, Documentatie niet goed geformateerd

**Comment by alextreme** [comment]
@HenriKorver zou jij Steven toegang kunnen geven tot de repository?

@stevenbal wees vrij om op te pakken.

**Comment by HenriKorver** [comment]
> @HenriKorver zou jij Steven toegang kunnen geven tot de repository?

Zojuist gedaan

**Comment by stevenbal** [comment]
@HenriKorver ik heb de badge geupdate en de formatting ook aangepast van de README: https://github.com/VNG-Realisatie/demo-api-component
