### ISSUE TITLE
Uitzoeken getpostman.com API voor het publiceren van collections (liefst met environment variabelen)

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#254]
# Taak

Uitzoeken getpostman.com API voor het publiceren van collections (liefst met environment variabelen):

https://docs.api.getpostman.com/?_ga=2.79238610.739636070.1564063721-1128833827.1542801720&version=latest

**Comment by stevenbal** [comment]
It seems that it is possible to create collections via getpostman's API, but I have not found a way to automatically publish these collections, which kind of defeats the point I guess. It is possible to create environments with the correct variables using the API though.
