### ISSUE TITLE
Als developer wil ik dat mijn secrets verborgen blijven (API key, JWT, password/secret)

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#264]
Als developer wil ik dat mijn secrets verborgen blijven zodat mensen niet mijn API token's of username/password kunnen overnemen.

Bij het toevoegen van de eigen api-test.nl API test kwamen we tegen dat de username/password terug komen op de testsessie detail-scherm. Dit mag natuurlijk niet voorkomen, net zoals het niet de bedoeling is dat de API keys of JWT's inzichtelijk zijn.

Hier zijn een aantal mogelijkheden voor, waarbij waarschijnlijk een combinatie nodig is om dit afdoende af te dekken:

 - variabelen met de term 'password' of 'key' of 'token' automatisch verbergen
 - de authorization-header / JWTs standaard verbergen op de sessie detail-pagina (of verbergen bij het bekijken door anderen)
 - uitzoeken of newman een optie heeft om 'secrets' niet op te nemen in de HTML reports die je ziet (in ieder geval controleren dat secrets hier niet in voorkomen)
 - een vinkje om aan te geven of de sessie-details al dan niet publiek ingezien mogen worden
 - verder? 

...

![Screenshot_2019-08-22_15-31-59](https://user-images.githubusercontent.com/226839/63518803-1da51a80-c4f2-11e9-9c3b-3bad865de056.png)

![Screenshot_2019-08-22_15-32-14](https://user-images.githubusercontent.com/226839/63518810-2138a180-c4f2-11e9-9d04-0cbf8667e9f6.png)

**Comment by stevenbal** [comment]
@HenriKorver omdat er binnen Newman geen optie is om bepaalde variabelen niet te laten zien in de HTML en JSON reports, doe ik nu een replace om de waardes van variabelen die gemarkeerd zijn als hidden (bijv. username en password) te vervangen met een placeholder `{hidden}`
![Screenshot from 2019-08-26 11-02-44](https://user-images.githubusercontent.com/29249171/63679241-2d25ab80-c7f1-11e9-8bb9-347d1c2f479f.png)

Het enige wat er dan nog overblijft is dat, bijv. in het geval van de test voor de API van het testplatform zelf, er ingelogd wordt via de API waarbij er een key teruggegeven wordt. Dit kan voor verschillende API's anders zijn, dus het is niet echt mogelijk om dit makkelijk eruit te filteren
![Screenshot from 2019-08-26 11-02-48](https://user-images.githubusercontent.com/29249171/63679244-2eef6f00-c7f1-11e9-85f3-c08e61083a07.png)

**Comment by HenriKorver** [comment]
Dus voor de ZGW-API's en de API van het API test Platform kunnen we het security probleem oplossen omdat we weten hoe het daar werkt. Als we andere API's willen testen op het platform zal dat vooralsnog elke keer maatwerk zijn. Ik zie ook zo snel niet een elegante generieke oplossing.

**Comment by alextreme** [comment]
Besproken met Henri en Steven

Een optie toevoegen om op Test scenario-niveau te configureren of de Newman HTML+JSON logs door derden gezien mogen worden.

Standaard staat dit aan, mocht een situatie zijn waarbij gevoelige gegevens uit een API terug komen dan heeft de ATP beheer-team de mogelijkheid om dit uit te schakelen.

**Comment by alextreme** [comment]
@stevenbal zou je vng-test hiermee kunnen updaten en daar dubbel-checken voor de zekerheid?

**Comment by stevenbal** [comment]
@alextreme ik heb gedeployed en nog eens gecheckt op test, en het werkt zoals gedacht.

**Comment by alextreme** [comment]
In orde, gecontroleerd met:

https://staging.api-test.nl/server/ccfd4f39-cc6a-4677-9e22-aa666ff4024c/
