### ISSUE TITLE
Als productowner wil ik een testset voor de OAS-specificatie van de ZGW API's

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#265]
zodat we de meest fundamentele testset voor de ZGW API's gereed hebben op het ATP voor live-gang.

**Toelichting**:
Momenteel wordt er al gewerkt aan een Postman script dat het gewenste gedrag van de ZGW API's test zoals dat beschreven is in het standaard.md document. Echter dit document beschrijft precies de aanvullende eisen die niet gespecificeerd kunnen worden in een OAS-specificatie. Dus het voorgestelde script is hierop een (noodzakelijke) aanvulling.

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by HenriKorver** [comment]
Ontwikkeling van dit script is onderdeel van het ZGW-project (zie https://github.com/VNG-Realisatie/gemma-zaken/issues/1233). Men is er nog niet aan begonnen. Echter succes van ATP project is hiervan afhankelijk.

**Comment by HenriKorver** [comment]
Bovendien kan user story #154 ook profiteren van dit script omdat je ermee de consumer testset kunt testen.

**Comment by alextreme** [comment]
Besproken met @joeribekker , besloten om dit 50/50 te doen met het ZGW project om zo dit zo snel mogelijk te realiseren.

**Comment by alextreme** [comment]
Focus dient te liggen op het ZRC, en de eventuele noodzakelijke ZTC calls om het testen van de ZRC te voltooien.

**Comment by stevenbal** [comment]
De testscripts zijn hier beschikbaar https://github.com/VNG-Realisatie/gemma-postman-tests/blob/master/ZGW_OAS_tests.json

Ik heb ze ook alvast op productie gezet https://api-test.nl/server/testscenario/12/

**Comment by HenriKorver** [comment]
@stevenbal Wat heb je dat snel gedaan, fantastisch! Kun je ook de bijbehorende variabelenlijst exporteren en die beschikbaar maken via een link? Dan kan ik het script ook zelf runnen in Postman

**Comment by stevenbal** [comment]
@HenriKorver ik heb de collection hier gepubliceerd: https://documenter.getpostman.com/view/7083537/SVfTMSWc?version=latest

Als het goed is, kun je met Run in Postman de collectie met de environment variabelen 'ZGW oas tests referentiecomponenten' runnen.

**Comment by HenriKorver** [comment]
@stevenbal Van de 146 calls falen er 66. Zijn dat allemaal fouten in de ZGW API's? Zo ja, heb je daarvoor een bug issue ingediend bij de github van ZGW?

**Comment by stevenbal** [comment]
@HenriKorver de bugfixes zijn inmiddels wel gemerged in de develop branches van de ZGW API's, alleen zijn de develop branches nog niet gemerged naar master en dus nog niet gedeployed naar de referentiecomponenten (dat zal op 18 september gebeuren).

Er zijn wel test componenten waarop deze bugfixes al doorgevoerd zijn, ik zal er vandaag en morgen voor zorgen dat die genoeg ingericht zijn om de tests op de kunnen draaien, om te laten zien dat de tests slagen.

**Comment by HenriKorver** [comment]
Postman collection moet nog aangepast worden naar aanleiding van een komende aanpassing van de ZGW API's (zie https://github.com/VNG-Realisatie/gemma-zaken/pull/1235)

**Comment by HenriKorver** [comment]
@stevenbal  Er zitten fouten in het testscript, zie https://github.com/VNG-Realisatie/api-test-platform/issues/290.

**Comment by stevenbal** [comment]
Doordat er veranderingen gekomen zijn in de OAS van het ZTC er er ook nog een nieuwe Autorisatie scope bij moet komen om de tests mogelijk te maken, zullen nog niet alle tests slagen momenteel

**Comment by alextreme** [comment]
Besproken. Henri heeft op zijn ZGW Github fork een badge geplaatst die (bij een slagende provder-run) groen wordt.

Op dit moment falen nog 23 van de 156 calls:
https://api-test.nl/server/11b4506c-005e-44ab-ac3f-06677979bf8b/

![Screenshot_2019-10-17_15-23-42](https://user-images.githubusercontent.com/226839/67012715-28df8580-f0f2-11e9-986e-7050e0107ec1.png)

**Comment by alextreme** [comment]
Blijft ter review voor Henri totdat er een badge gepubliceerd is op de ZGW referentieimplementatie github

**Comment by HenriKorver** [comment]
Graag zou ik dit scriptje aangepast zien zodat het scriptje niet meer afhankelijk is van delete rechten op de ZTC. Dit zal het aantal errors enorm reduceren en de ware bugs aan het licht brengen

**Comment by HenriKorver** [comment]
Het probleem hangt dus samen met https://github.com/VNG-Realisatie/gemma-zaken/issues/1351 waarin wordt verzocht om delete rechten toe te voegen voor ZTC. Dit issue is gesloten maar ik begrijp eigenlijk niet waarom.
@stevenbal Weet jij dat?
Hoe dan ook is het verstandig om niet afhankelijk te zijn van het ZGW-project lijkt het.

**Comment by stevenbal** [comment]
@HenriKorver vng-realisatie/gemma-zaken#1351 is gesloten omdat het al geimplementeerd is en inmiddels gemerged is in develop, de feature staat alleen nog niet op de gehoste versie (https://catalogi-api.vng.cloud)

**Comment by alextreme** [comment]
Inmiddels slagen de OAS tests.

Wel komt het probleem van de lege bodies in de responses nog wel voor bij eerdere scheduled tests. We zijn er dus nog niet achter waardoor dit komt, en dit zorgt later in de OAS script voor falende tests als het gebeurt.

@stevenbal kan hier de hulp van @sergei-maertens goed gebruiken om het gedrag te debuggen. Het kan een probleem zijn bij newman, of de ZGW componenten of de simultane tests of de infrastructuur.

Een mogelijkheid om dit te narrowen is om de OAS script ook uit te voeren op de OpenZaak test-omgeving.

Ik zou adviseren om voor een bepaalde case waar dit voorkomt de ZGW-logs te bekijken of het verzoek wel of niet daar is aangekomen.

![Screenshot_2019-11-28_16-08-55](https://user-images.githubusercontent.com/226839/69817059-01ec9700-11fa-11ea-9f8d-426ec1991396.png)

**Comment by stevenbal** [comment]
@alextreme ik heb geprobeerd om het probleem lokaal te reproduceren (met zowel de newman CLI als de newman library voor node) op de dockers van gemma-zaken, maar ik liep niet tegen hetzelfde probleem aan, dus ik zal er morgen/donderdag met Sergei nog eens naar kijken

**Comment by alextreme** [comment]
Zoals besproken vermoed ik dat dit probleem alleen speelt bij de infrastructuur van ZGW. Dit lijkt mij waarschijnlijker dan dat het aan newman of de ZGW dockers zelf zou kunnen liggen, al zou je nog wel voor de zekerheid de versie van newman op de productie-omgeving kunnen checken.

@kciredor heb jij soms inzicht in de logging van de requests/responses naar de ZGW componenten? We lopen tegen een vreemde bug aan waarbij tijdens het automatisch testen van de componenten de responses van API verzoeken leeg zijn, het lijkt vrij random op te treden.
Als je hier inzicht in hebt dan kan @stevenbal een tijdstip en een request-URL (vlak na 24:00 elke dag) aangeven waarmee dit is opgetreden.

Als deze informatie niet op K8s-niveau wordt gelogd dan wachten we even totdat Sergei hier tijd voor heeft.

**Comment by stevenbal** [comment]
@alextreme na het een aantal keer met mijn lokale newman te runnen op de gehoste referentiecomponenten heb ik het kunnen reproduceren. 
```html
Maak een ZAAK-INFORMATIEOBJECT relatie aan.
  POST https://zaken-api.vng.cloud/api/v1/zaakinformatieobjecten [errored]
     ESOCKETTIMEDOUT
  6. Maak een ZAAK-INFORMATIEOBJECT relatie aan geeft 201
```


Newman logt alleen niet de timestamps van de requests, dus ik weet alleen dat het probleem optrad tussen  00:00:57 en 00:01:02 op 29 november

**Comment by alextreme** [comment]
@stevenbal helder en fijn dat je het hebt kunnen reproduceren tegen de gehoste componenten, je kan in dat geval proberen met de newman timeout-request parameter:

https://community.getpostman.com/t/error-callback-timed-out-why/1508

De timeout zou kunnen komen door infrastructuur, maar ik bedenk me ook dat dit vooral (alleen?) voor lijkt te komen bij POSTS naar endpoints waar ik een verbinding naar een ander component zou verwachten (DNS? duurt te lang?)

Als het hier aan zou liggen dan heb ik nog een reden waarom een monolith verstandiger is om mee te beginnen :)

**Comment by kciredor** [comment]
Hi,

Op https://monitoring.haven.vng.cloud/ draait ElasticSearch behorend bij het cluster waar ZGW api's in draaien.

Alles binnen kubernetes, inclusief de bewegende delen van kubernetes zelf en inclusief alle pods zoals die van ZGW, gaat naar ElasticSearch. Dat wil zeggen: stdout + stderr. Dus als de request / response volledig in stdout of stderr geprint worden, dan komen ze ook volledig in ElasticSearch.

Ik heb reeds in september toegang gegeven aan Sergei en Joeri tot ElasticSearch, die account is nog actief. Helaas heb ik net wel de database moeten clearen, want de disk zat vol :-) Kan een cleanup jobje gebruiken. Anyway: nu een veel grotere disk en ik zie dat jullie de issue kunnen reproduceren dus dat is mooi. Als je dat nu doet en je logged in op Elastic kun je alles zien in realtime.

Mocht de root cause op de infra uitkomen verneem ik het graag, dan zal ik het fixen.

PS: DNS intern in het cluster is Weave en die is erg rap, externe resolving gaat via 1.1.1.1 en 8.8.8.8 en die zijn ook snel. Je kunt het verifiëren door in een van de ZGW pods te bashen en e.g. dig runnen.

Hoop dat dit helpt!

Groet, Roderick

**Comment by stevenbal** [comment]
@alextreme ik denk dat je gelijk hebt, ik heb een grotere waarde gezet voor `timeout-request` en dan verlopen 10 runs achter elkaar zonder problemen (en duurt de traagste request ook een stuk langer, dus het lag idd aan de timeout)

**Comment by alextreme** [comment]
@kciredor dank voor de details! Voor nu niet nodig maar wellicht bij een toekomstige ZGW-issue.

@stevenbal mooi dat we er dan achter lijken te zijn, ik ben wel benieuwd wat dan de default-timeoutwaarde is in newman. Wees vrij om het op te hogen in api-test.nl en te kijken of dit voor consistente testresultaten zorgt.

**Comment by stevenbal** [comment]
@alextreme @HenriKorver de verhoogde timeout lijkt het probleem inderdaad op te lossen https://api-test.nl/server/1/be77d2e9-6843-47f9-b2d3-d426e92f1562/07dec482-0ef3-40b8-9d89-04401f880a2e/

Ik weet niet wat de default timeout is van newman, maar bij onze runner stond hij eerst op 5 seconden, wat dus duidelijk niet genoeg was :p

**Comment by HenriKorver** [comment]
Goed werk! Wat is de timeout nu?

**Comment by stevenbal** [comment]
Ik heb voor de zekerheid maar 50 seconden gedaan :)

**Comment by HenriKorver** [comment]
Heel blij dat ik eindelijk vlak voor het einde van het jaar dit issue kan sluiten
