### ISSUE TITLE
Shields.io - Trage badges bij nieuwe provider-runs

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#266]
De shields van shields.io reageren in de ervaring van @HenriKorver erg traag, het duurt soms een paar minuten voordat deze op een Github Markdown pagina zichtbaar worden.

Of hier iets aan te doen valt met shields.io is nog maar de vraag. Dus deze user story is met name bedoeld om te analyseren waar het probleem ligt.

**Comment by stevenbal** [comment]
Ik heb er even naar gekeken, maar helaas lijkt het erop dat er niet veel aan te doen valt van onze kant, het hangt af van de hoeveelheid requests die shields.io binnen krijgt (zie: https://github.com/badges/shields/issues/1568)

**Comment by HenriKorver** [comment]
Bedankt voor de analyse. Dan laten we het voor nu even zitten.
