### ISSUE TITLE
Consumer testing: Bij het starten van een sessie blijft de status op 'starting' totdat ik refresh

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#268]
Henri: Bij het starten van een sessie blijft de status op 'starting' totdat ik refresh/F5.

Dit is volgens mij afhankelijk van hoe snel de nieuwe sessie wordt aangemaakt. Ik krijg in ieder geval bij het testen wel meteen een 'running' status met endpoints, Henri moet echter F5'en om dit te zien.

Als oplossing zou het wenselijk zijn dat er (vergelijkbaar met het Docker/K8s status check) ook voor reguliere sessies met status 'starting' elke seconden wordt gepolled of de status inmiddels 'running' is.

**Comment by stevenbal** [comment]
Als het goed is zou er bij reguliere sessies al status checks gedaan moeten worden, maar ik zal even kijken waar het mis gaat.

**Comment by stevenbal** [comment]
De update om de session ids te unlocalizen was nog niet doorgevoerd op staging, ik heb hem nu wel gedeployed en bij mij werkt het.

@HenriKorver zou je het kunnen testen op https://vng-staging.maykin.nl/?

**Comment by HenriKorver** [comment]
Top, bij mij werkt het nu ook
