### ISSUE TITLE
Admin: check django-admin-index en update admin_overrides vanuit default project

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#269]
Ergens is onze mooie django-admin-index menu verdwenen toen ik de admin_overrides.css wou updaten.

Graag uitzoeken en het menu herstellen. Ik weet dat die admin_overrides.css door de root .gitignore standaard niet wordt meegenomen, maar ik heb het iets andere kleuren gegeven wat voor een wat frissere uitstraling van de admin zorgt.

**Comment by stevenbal** [comment]
@alextreme door gulp werden de aanpassingen die je gedaan had aan admin_overrides.css vervangen door admin_overrides.scss, dus ik heb die laatste file even een andere naam gegeven, zodat er nu bij het deployen niet de hele tijd aanpassingen aan admin_overrides.css gemaakt worden

**Comment by stevenbal** [comment]
ik heb ook de dependency van django-admin-index veranderd naar een github link en gedeployed op test, dus daar is het menu weer te zien (https://vng-test.maykin.nl/admin/)

**Comment by alextreme** [comment]
Helder. Graag staging ook deployen en een PR van develop naar master doen, dan updaten we api-test.nl ook hiermee.

**Comment by stevenbal** [comment]
@alextreme gedaan!

**Comment by alextreme** [comment]
Gechecked, super merci!
