### ISSUE TITLE
Consumer tests: Scenario cases aanvullen met een omschrijving

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#270]
Genoemd door @HenriKorver 

Het zou prettig zijn om per scenario case een omschrijving van de case op te nemen via de admin.

Deze zou dan per case boven de case weergegeven worden op de session type detail-scherm en op de session report-scherm.

**Comment by alextreme** [comment]
Bij deze beschikbaar via het vraagtekentje per case:

https://staging.api-test.nl/consumer/84b567c3-a4fb-4b7c-bab3-796e37037dde/report/

https://staging.api-test.nl/admin/testsession/scenariocase/54/change/?_changelist_filters=collection__id__exact%3D16

**Comment by HenriKorver** [comment]
Vraagtekentje vind ik verwarrend. Men heeft de neiging erop te willen klikken in plaats van eroverheen te bewegen met de muis. Kan het click-event uitgeschakeld worden?

**Comment by alextreme** [comment]
Bij deze alleen zichtbaar on-hover:

https://staging.api-test.nl/consumer/84b567c3-a4fb-4b7c-bab3-796e37037dde/report/

**Comment by HenriKorver** [comment]
Bij nader inzien vind ik dit niet intuïtief werken. Kunnen jullie toch maar na de eerste kolom (http method) een extra kolom toevoegen (beschrijving) met de omschrijving van de method.

**Comment by stevenbal** [comment]
Description is nu een lege string i.p.v. None:
![Screenshot from 2019-10-21 09-52-49](https://user-images.githubusercontent.com/29249171/67186570-a05e2f00-f3e8-11e9-81b7-11fa3f5cb5c3.png)
https://test.api-test.nl/consumer/sessiontype/5/

En de description is toegevoegd aan de inline in ScenarioCaseCollection admin:
![Screenshot from 2019-10-21 09-53-41](https://user-images.githubusercontent.com/29249171/67186631-bff55780-f3e8-11e9-935c-ce9e2dd60f0a.png)
https://test.api-test.nl/admin/testsession/scenariocasecollection/31/change/

**Comment by stevenbal** [comment]
Description is nu een lege string i.p.v. None:
![Screenshot from 2019-10-21 09-52-49](https://user-images.githubusercontent.com/29249171/67186570-a05e2f00-f3e8-11e9-81b7-11fa3f5cb5c3.png)
https://test.api-test.nl/consumer/sessiontype/5/

En de description is toegevoegd aan de inline in ScenarioCaseCollection admin:
![Screenshot from 2019-10-21 09-53-41](https://user-images.githubusercontent.com/29249171/67186631-bff55780-f3e8-11e9-935c-ce9e2dd60f0a.png)
https://test.api-test.nl/admin/testsession/scenariocasecollection/31/change/

**Comment by stevenbal** [comment]
Nu ook op staging:
https://staging.api-test.nl/consumer/sessiontype/5/

https://staging.api-test.nl/admin/testsession/scenariocasecollection/21/change/

**Comment by alextreme** [comment]
Lijkt mij zo in orde, ter controle
