### ISSUE TITLE
Dubbel-check mailafhandeling op api-test.nl

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#275]
# Taak

ivo kreeg geen registratie/activatie mail binnen. Kijken hoe dit nu staat ingesteld en of hier nog iets voor nodig is aan onze kant.

**Comment by stevenbal** [comment]
Het lukt mij niet om deze bug te reproduceren, ik kreeg binnen enkele seconden gelijk een mail terug na registratie op productie
![Screenshot from 2019-09-16 09-33-54](https://user-images.githubusercontent.com/29249171/64940803-42787d80-d865-11e9-8134-885036153c72.png)

**Comment by HenriKorver** [comment]
Ik heb zojuist met VNG systeembeheer gesproken en het probleem lag aan onze kant. Het domein api-test.nl werd geblokkeerd door de mail server van VNG, maar staat nu weer op de white-list. Probleem opgelost.
