### ISSUE TITLE
Script om op basis van een OpenAPI spec de Scenario cases aan te maken

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#277]
Wat mij betreft zou dit goed te combineren zijn in de admin, door op Scenario Case collections een importeer-functie te hebben. Dit zou via een URL of door een OAS-file up te loaden uitgevoerd kunnen voeren.

@HenriKorver wees vrij om deze story indien gewenst verder uit te breiden.

**Toelichting**:
...

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by alextreme** [comment]
Bugje waar ik tijdens het testen tegenaan liep:

https://sentry.maykinmedia.nl/maykin-media/vng-testplatform-staging/issues/260571/?query=is:unresolved

**Comment by alextreme** [comment]
Werkt inmiddels zoals het hoort:

![Screenshot_2019-10-10_14-05-53](https://user-images.githubusercontent.com/226839/66567324-3aabb080-eb67-11e9-9200-026768316ac8.png)


https://staging.api-test.nl/admin/testsession/scenariocasecollection/21/change/

![Screenshot_2019-10-10_14-06-28](https://user-images.githubusercontent.com/226839/66567327-3e3f3780-eb67-11e9-8402-40c2d009eabc.png)

**Comment by HenriKorver** [comment]
Van welk Session Type is deze Scenario Case Collection (ZGW Collection) onderdeel? Hoe kan ik dat zien in de Admin? Dit heb je nodig om het daadwerkelijk te kunnen testen lijkt me...

**Comment by HenriKorver** [comment]
@alextreme @stevenbal Kan één van jullie mijn bovenstaande vraag beantwoorden?

**Comment by stevenbal** [comment]
@HenriKorver van het zgw session type: https://staging.api-test.nl/consumer/sessiontype/10/

**Comment by HenriKorver** [comment]
@stevenbal Dank!

**Comment by stevenbal** [comment]
Ik heb een sessie aangemaakt en de ZGW oas tests gerund op de exposed urls van die sessie.

Sessie:
https://api-test.nl/consumer/fc813d49-c1c2-4f65-bf64-8ae00064bf76/

OAS provider tests:
https://api-test.nl/server/be77d2e9-6843-47f9-b2d3-d426e92f1562/eaa131d4-6742-4794-994d-1806c54613a0/

Zoals je kunt zien zijn er nog 30-40 die volgens de session niet gecalld zijn, daar zijn de volgende redenen voor:

- In de scenario cases wordt expliciet gekeken of de queryparameters ook aanwezig zijn, als dat niet het geval is wordt de call niet meegeteld. Ik zal zorgen dat de queryparameters die ontbreken toegevoegd worden aan de tests

Er blijven wel twee problemen:
- De calls die uit de OAS tests gehaald zijn, omdat de endpoints niet direct aangesproken dienen te worden (bijv. POST op `ZaakBesluit`), worden natuurlijk wel meegenomen bij het automatisch gegeneren van de OAS, dus die zouden dan ook uit de scenario case collectie gehaald moeten worden (hetzelfde geldt voor de publish endpoints in het ZTC totdat de benodigde autorisatie scope er is)
- In het NRC zit er op `Abonnement` nu validatie die checkt of de `Abonnement.callbackUrl` een 403 geeft als er zonder JWT een request naar gedaan wordt en of er een 204 terugkomt als er wel een JWT meegegeven wordt. Het probleem hiermee is dat het niet mogelijk is om met de Postman mock server verschillende responses terug te geven op een gemockte url op basis van headers (de Authorization header in dit geval)

**Comment by alextreme** [comment]
@stevenbal ter update aangezien deze al een tijdje bij mij hangt. Mag na je input door naar Henri

**Comment by stevenbal** [comment]
@HenriKorver @alextreme ik heb de nog eens de ZGW oas testscripts op de urls van een consumer sessie uitgevoerd, en als de provider test slaagt, dan zijn ook alle scenario cases groen en slaagt de consumer sessie ook:

link naar provider test: https://api-test.nl/server/1/9bee4f0c-ffda-4f86-8db6-8e8821b02490/
link naar consumer sessie: https://api-test.nl/consumer/1/43ac185d-bd22-4336-afd7-1400d5494132/

**Comment by HenriKorver** [comment]
Dank, dit is uitstekend werk!
