### ISSUE TITLE
Retrospective Sprint 1

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-test-platform#28]

**Comment by alextreme** [comment]
JW: Verbazing over de snelheid, soepelheid, Henri doet het prima. Wel graag strakker/duidelijker hebben over de lopende taken (meer timeboxen).
HK: Met ZDS is het wat strakker qua planning (planning/backlog refinement/demo: vaste dagen bepaalde onderdelen in agenda).
JW: Qua planning doen we deze 3 onderwerpen binnen 1 sessie. Zullen zeker sprint 2 de onderwerpen vooruit plannen.
HK: Behoefte om meer 1-op-1 inhoudelijk qua techniek te sparren. Graag tijd hiervoor vrijmaken / timeboxen.
AdL: Sprint is verholpen zoals het hoort, volgens mij groeit iedereen in zijn rol

->

Iets beter timeboxen, iets duidelijker afbakenen onderdelen, meer ruimte inhoudelijke discussies

**Comment by TCIMEddy** [comment]
mooi lekker strak verslag en retro. Niet teveel poespas hahaha
