### ISSUE TITLE
Bij registratie de nieuwe gebruiker er goed op wijzen dat de confirmatie-mail in de spamfolder kan belanden!

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#282]
# Taak

Bij registratie de nieuwe gebruiker er goed op wijzen dat de confirmatie-mail in de spamfolder kan belanden!

**Comment by alextreme** [comment]
Bevestigd op staging:

![Screenshot_2019-09-26_18-58-40](https://user-images.githubusercontent.com/226839/65708811-b13cae80-e08f-11e9-83fb-4607b1c3fa75.png)
