### ISSUE TITLE
Status bar blijft lange tijd leeg zonder een percentage aan te geven

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#283]
# Bug

Eerst zie je een lange tijd een lege status bar zonder percentage (op productie):

![afbeelding](https://user-images.githubusercontent.com/37145898/64987402-5fdf3300-d8c9-11e9-8455-023a84eea5f1.png)

Een daarna faalt het:

![afbeelding](https://user-images.githubusercontent.com/37145898/64987642-e6941000-d8c9-11e9-96af-0017b102f81b.png)

**Comment by alextreme** [comment]
Statusbar werkt bij mij op staging zoals verwacht:

![Screenshot_2019-09-26_19-02-09](https://user-images.githubusercontent.com/226839/65709048-3627c800-e090-11e9-8662-4def3257e1d7.png)

**Comment by HenriKorver** [comment]
Graag uitrollen naar productie
