### ISSUE TITLE
(Scheduled) badge werkt niet

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#284]
# Bug

Onderstaande scheduled badge afkomstig uit https://api-test.nl/server/719f6829-2987-4dea-a4b7-8e5c07072245/ komt niet uit op een testrapport als je erop klikt.

[![Status badge](https://img.shields.io/endpoint.svg?style=for-the-badge&url=https%3A//api-test.nl/api/v1/provider-latest-badge/BRP%2520Basis%2520Ingeschreven%2520Persoon%2520API%2520tests/henri/)](https://api-test.nl/api/v1/provider-latest-badge/BRP%20Basis%20Ingeschreven%20Persoon%20API%20tests/henri/)

De andere statische badge werkt wel.

**Comment by HenriKorver** [comment]
Onderstaande scheduled badge afkomstig uit https://api-test.nl/server/719f6829-2987-4dea-a4b7-8e5c07072245/ werkt niet

[![Status badge](https://img.shields.io/endpoint.svg?style=for-the-badge&url=https%3A//api-test.nl/api/v1/provider-latest-badge/BRP%2520Basis%2520Ingeschreven%2520Persoon%2520API%2520tests/henri/)](https://api-test.nl/api/v1/provider-latest-badge/BRP%20Basis%20Ingeschreven%20Persoon%20API%20tests/henri/)

De andere statische badge werkt wel.

**Comment by stevenbal** [comment]
dat zal wel door shields.io komen dan, want bij mij doen beide badges het in het linkje wat je stuurde

**Comment by alextreme** [comment]
@stevenbal waarschijnlijk heeft Henri de badge verwisseld of aangepast in de markdown.

Zou je de volgende markdown zoals getoond op de link hierboven kunnen dubbelchecken? Ik vermoed dat de spaties in de Test Scenario naam niet gaat werken en dat je hier een ID moet gaan gebruiken in je URLs:

`[![Status badge](https://img.shields.io/endpoint.svg?style=for-the-badge&url=https%3A//api-test.nl/api/v1/provider-latest-badge/BRP%2520Basis%2520Ingeschreven%2520Persoon%2520API%2520tests/henri/)](https://api-test.nl/api/v1/provider-latest-badge/BRP%20Basis%20Ingeschreven%20Persoon%20API%20tests/henri/)`

**Comment by stevenbal** [comment]
@alextreme ik denk dat het handiger is als ik deze aanpassing voor de laatste badge samen neem met de andere aanpassingen voor de provider test structuur, omdat het waarschijnlijk toch op de schop moet daarvoor

**Comment by stevenbal** [comment]
het endpoint gebruikt nu de uuid van het environment dat gebruikt is voor de provider run, die vastgezet is op een test scenario en een user (https://github.com/VNG-Realisatie/api-test-platform-code/commit/6eaddd8caa3792bd44016e18f6fe1c95a89d9adf)

**Comment by stevenbal** [comment]
@HenriKorver @alextreme het webinterface maakt nu onderscheid tussen scheduled provider runs en gewone provider runs. Stel ik heb een bepaald test scenario en een environment bij dat test scenario, ik heb een schedule ingesteld daarvoor en ik heb een gewone provider run uitgevoerd voor dat test scenario + environment: moeten de resultaten van de gewone provider runs ook verschijnen in de lijst met provider runs voor het scheduled scenario (en vice versa)? En moeten de scheduled scenarios en gewone provider runs dus dezelfde badge gebruiken of niet?

**Comment by alextreme** [comment]
Uitgangspunt was dat de 'one off' provider runs en de 'scheduled' provider runs gescheiden waren qua lijstweergave, dit aangezien er volgens mij andere gegevens per type run worden getoond en om het verschil duidelijk te maken.

Het is aan @HenriKorver om aan te geven mocht dat gecombineerd moeten worden (wellicht als we het onderscheid gaan maken qua lijstweergave per soort test scenario), maar daar moeten we het eerst over hebben.

Qua badges dienen deze visueel gelijk te zijn. De onderliggende werking zal (vermoed ik) anders blijven, maar ik weet ook dat hier behoorlijk wat aan gesleuteld is en dat eerst overleg hierover nodig is om door te kunnen.

**Comment by alextreme** [comment]
Zelfde probleem als met de andere scheduled issue ( #267 ).

Besproken en de wens is om de zaken te combineren binnen een environment (scheduled en one-off provider runs). De actie is om een environment voor een bepaalde API in te richten, en dan kan later bepaald worden of deze automatisch wordt getest of niet.

**Comment by alextreme** [comment]
@stevenbal nog even kijken naar de 'Custom badge - Resource not found' melding. Als er nog geen run is uitgevoerd dan dient de badge verborgen te zijn.

**Comment by stevenbal** [comment]
Op test wordt de badge nu verborgen zo lang er nog geen resultaten zijn
![Screenshot from 2019-10-17 11-37-56](https://user-images.githubusercontent.com/29249171/66997422-b90dd280-f0d2-11e9-89ab-517a640ad598.png)

Ook op de provider run detail pagina
![Screenshot from 2019-10-17 11-38-34](https://user-images.githubusercontent.com/29249171/66997423-bad79600-f0d2-11e9-9564-a4026056d359.png)

**Comment by stevenbal** [comment]
Het verbergen van de badges als er nog geen resultaten zijn is nu ook live op staging
