### ISSUE TITLE
Verschillende API's noemen in menu en op dashboard

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#287]
...zodat het duidelijker is welke APIs het ATP ondersteunt.

**Toelichting**:
Mijn beeld is dat het nog niet duidelijk is welke API's worden ondersteunt op api-test.nl, en ik denk dat daar nu juist de interesse is van gebruikers. Eigenlijk wil je dat in 1 oogopslag duidelijk is welke APIs via het ATV beschikbaar zijn.

Termen zoals 'Provider' en 'Consumer' zijn voor ons van belang, maar ik denk dat een gebruiker van het testplatform meer geintereseerd is in het inzetten van api-test.nl voor een specifieke API.

Bovendien kan een andere weergave zorgen voor meer 'ownership' van de APIs door de verschillende VNG teams.

Hoe het zou kunnen (met een extra laag ertussen):

![Screenshot_2019-09-27_10-28-50](https://user-images.githubusercontent.com/226839/65754765-07eacc80-e112-11e9-9dbb-06212da61d83.png)

Hoe het nu is:
![Screenshot_2019-09-27_10-27-03](https://user-images.githubusercontent.com/226839/65754743-fbff0a80-e111-11e9-9aae-f15e012ef84d.png)

Ter bespreking

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by HenriKorver** [comment]
Goed voorstel! Alvast een paar opmerkingen uit de losse pols:

* Het topmenu heeft nu als titel TEST PROVIDER. Dat lijkt me een ongelukkige naam omdat je hier nog niet de keuze wilt maken of je de provider of de consumer van de API in kwestie gaat testen. Wellicht beter om hier de menutitel gewoon weg te laten.

* ZGW API bestaat weer uit meerdere  API's (Zaken API, Documenten API, Catalogi API, etc.). Daarvoor zullen we een vergelijkbaar sub-menu moeten inrichten. Dus nog een extra laag ertussen.

**Comment by HenriKorver** [comment]
@alextreme Verder vind ik dit voorstel duidelijk genoeg om mee aan de slag te gaan. Dus als je wilt mag je het in de sprint slepen.

**Comment by alextreme** [comment]
Laten we het eerst even samen met Steven uitgebreider bespreken. Je opmerking over het kunnen starten van tests voor ZGW sub-API's levert bij mij vragen op, en ik wil nog even sparren over de consumer vs provider onderscheid.

**Comment by alextreme** [comment]
Besproken:
- eerst kies je de API (BRP, Demo, ZGW)
- dan kies je tussen consumer en provider
- dan kies je de test scenario / session type 

Onderscheid tussen ZGW APIs wordt gedaan op test scenario / session type niveau.

**Comment by JanWillemKooi** [comment]
Flat page aanmaken in de dashboard

**Comment by alextreme** [comment]
@stevenbal mij lijkt het netter om de uitklap-menuitem te gebruiken (zie bij Buttons):

https://coreui.io/demo/#main.html

![Screenshot_2019-10-17_14-55-57](https://user-images.githubusercontent.com/226839/67010643-54f90780-f0ee-11e9-9abc-2b915fcf3675.png)

**Comment by alextreme** [comment]
Daarnaast is het wenselijk om de naam van de geselecteerde API te tonen in de verschillende list-views. Als ik nu ATP API of ZGW API op de test-omgeving selecteer dan zie ik niet bij welke van die 2 API's ik ben:

https://test.api-test.nl/server/1/

![Screenshot_2019-10-17_15-42-46](https://user-images.githubusercontent.com/226839/67014352-026f1980-f0f5-11e9-9b3a-4004bb200b0f.png)

**Comment by stevenbal** [comment]
BIj deze is de dropdown veranderd naar het uitklapmenu van Coreui en is de API naam weergegeven bij de lijstweergaven van provider tests en consumer sessions

![Screenshot from 2019-10-21 09-45-32](https://user-images.githubusercontent.com/29249171/67186095-9425a200-f3e7-11e9-91a7-15b0f0593923.png)
https://test.api-test.nl/server/1/
https://test.api-test.nl/consumer/1/

**Comment by alextreme** [comment]
Het automatisch uitklappen van de submenu's werkt in mijn ogen niet echt lekker, het werkt alleen op de list-view (niet de detail-view) en het activeert na de page-load wat afleidend werkt.

Als het niet anders kan dan zou ik aanraden om de submenu's standaard uitgeklapt te houden.

**Comment by stevenbal** [comment]
@alextreme de aanpassingen hiervoor staan inmiddels op staging

**Comment by alextreme** [comment]
De werking qua scheiding van de verschillende APIs maakt het gebruik van het ATP in mijn ogen een stuk fijner.

@HenriKorver wees vrij om te reviewen.

**Comment by HenriKorver** [comment]
Ja werkt prima
