### ISSUE TITLE
Schedule date and last run do not match

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#288]
# Bug

Het lijkt of  er een tijdzone verschil zit van twee uur tussen het tijdstip van de geplande run en het tijdstip waarop de run daadwerkelijk heeft plaatsgevonden:

![afbeelding](https://user-images.githubusercontent.com/37145898/65831563-6d2df180-e2bb-11e9-8705-d81abea7ed8e.png)

**Comment by alextreme** [comment]
Besproken. Wachten tot morgen ter controle.

**Comment by stevenbal** [comment]
Op staging zijn de scheduled tests goed en op het juiste tijdstip uitgevoerd

![Screenshot from 2019-10-04 10-13-24](https://user-images.githubusercontent.com/29249171/66191921-b00f1100-e68f-11e9-98fd-3b6ac0f1bb7a.png)

**Comment by HenriKorver** [comment]
Alleen de schedule en de last run gebruiken nu nog verschillende display formaten wat verwarrend is:
00:01 versus 12:01 p.m. Graag harmoniseren. Ik prefereer het eerst formaat voor beide (00:01)

**Comment by stevenbal** [comment]
Op staging zijn de datetimes nu hetzelfde:
![Screenshot from 2019-10-21 11-02-28](https://user-images.githubusercontent.com/29249171/67191671-4ebaa200-f3f2-11e9-8a90-5f9a81aa1066.png)
https://staging.api-test.nl/server/db5f1a44-dc3b-438c-9f52-678d68bb0288/fc1eec78-41b3-4482-a4c2-fcd6a8419c83/
