### ISSUE TITLE
HTTP methods niet zichtbaar op detailpagina provider run

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#289]
# Taak

HTTP methods (GET, POST, PUT, etc.) van postman collection niet zichtbaar op detailpagina provider run:
![afbeelding](https://user-images.githubusercontent.com/37145898/65831711-55f00380-e2bd-11e9-897d-095736268052.png)

**Comment by alextreme** [comment]
Bij deze zijn ze zichtbaar op staging:

![Screenshot_2019-10-10_13-59-26](https://user-images.githubusercontent.com/226839/66566844-3fbc3000-eb66-11e9-9cb7-493445ec5650.png)

**Comment by JanWillemKooi** [comment]
Opmenrkingen:
HTTP Call voor de URL
Geen dubbele vinkjes (alleen die van de test zelf)

**Comment by alextreme** [comment]
Gereed op staging:

https://staging.api-test.nl/server/8e01d069-4d7d-439e-93a6-2188ad671d9a/

![Screenshot_2019-10-17_16-42-14](https://user-images.githubusercontent.com/226839/67019536-1b7bc880-f0fd-11e9-959e-a21815d09b4d.png)
