### ISSUE TITLE
Provider run en gepubliceerde postman collectie zijn niet in overeenstemming

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#290]
# Bug

De provider run ZGW OAS testscripts
https://api-test.nl/server/f2edfdd4-55d6-4486-b265-02114400e7d2/

bestaat uit 143 calls:

![afbeelding](https://user-images.githubusercontent.com/37145898/65832074-42926780-e2c0-11e9-9bab-48793b741699.png)

Echter als je de gepubliceerde postman collectie 

https://documenter.getpostman.com/view/7083537/SVmsVLTd?version=latest

importeert in Postman dan zijn er 156 calls:

![afbeelding](https://user-images.githubusercontent.com/37145898/65832139-8dac7a80-e2c0-11e9-9670-513b801e479e.png)

Bovendien knalt het script erna 14 calls uit
![afbeelding](https://user-images.githubusercontent.com/37145898/65832012-d9aaef80-e2bf-11e9-856f-3425bb5b81c4.png)

Dit lijkt niet niet te gebeuren op het testplatform waar de test helemaal afgerond wordt ondanks de fouten

**Comment by stevenbal** [comment]
@HenriKorver dat komt doordat bepaalde operaties uit de OAS niet uitgevoerd kunnen worden. Bijvoorbeeld het aanmaken van een `ZaakBesluit` via het endpoint in het ZRC (omdat dit endpoint niet aangesproken dient te worden door consumers, maar automatisch wordt aangesproken als er een `Besluit` aan een `Zaak` gekoppeld wordt in het BRC). 

Hetzelfde geldt voor `ObjectInformatieObject` in het DRC en het publiceren van resources in het ZTC, omdat er momenteel nog geen scope is waarmee gepubliceerde resources verwijderd kunnen worden

**Comment by HenriKorver** [comment]
@stevenbal Ik heb nog even verder gekeken en volgens mij is het gewoon een fout in het testscript. Het script faalt bij het aanmaken van een klantcontact en dat is logisch omdat in de aanroep steeds dezelfde identificatie wordt meegegeven, namelijk "klantcontact", waardoor je een foutmelding krijgt omdat er al een klantcontact bestaat met dezelfde identificatie.
```
{
  "zaak": "https://zaken-api.vng.cloud/api/v1/zaken/0bb8a9fd-c8ed-44eb-8379-e8b0d9c0901d",
  "identificatie": "klantcontact",
  "datumtijd": "2019-08-29T14:14:21Z",
  "kanaal": "string"
}

{
    "type": "https://zaken-api.vng.cloud/ref/fouten/ValidationError/",
    "code": "invalid",
    "title": "Invalid input.",
    "status": 400,
    "detail": "",
    "instance": "urn:uuid:62f4cb39-7273-499f-b414-9e7c9c0625e6",
    "invalidParams": [
        {
            "name": "identificatie",
            "code": "unique",
            "reason": "Er bestaat al een klantcontact met eenzelfde identificatie."
        }
    ]
}
```
Als je in de aanroep het element `identificatie` weglaat wordt er automatisch een unieke identificatie aangemaakt en dan gaat het wel goed. Althans het script komt dan een stuk verder.

**Comment by stevenbal** [comment]
Goed punt, bij klantcontact kan die issue idd makkelijk verholpen worden, heb de nieuwe versie van de tests ook op api-test.nl gezet.

**Comment by alextreme** [comment]
Besproken. Verschil is dat Postman stopt bij een error, en Newman gaat door met de volgende requests.

Besluit is om de niet-werkende requests uit de OAS script te halen. Het gedrag tussen componenten testen is alleen testbaar in de uitgebreide ZGW Postman collection.

**Comment by stevenbal** [comment]
ik heb de requests die werden overgeslagen uit de OAS tests gehaald https://api-test.nl/server/testscenario/12/

**Comment by alextreme** [comment]
@stevenbal werkt deze OAS script nu dan wel op productie?

**Comment by alextreme** [comment]
OAS script wordt uitgevoerd conform verwachting. URL van hierboven waarop de gepubliceerde Postman collection inzichtelijk is staat nu op:

https://api-test.nl/server/1/testscenario/12/
![Screenshot_2019-11-14_15-06-25](https://user-images.githubusercontent.com/226839/68863817-5834e280-06f0-11ea-8b54-5d5804ddd90d.png)

**Comment by alextreme** [comment]
@HenriKorver issue gaat inmiddels na een paar verschillende onderwerpen niet meer over de oorspronkelijke bug (die verholpen was in de test-script). OAS test-script slaagt inmiddels (soms) tegen de referentieomgeving. 

Graag horen we het of hier nog iets voor nodig is.

**Comment by HenriKorver** [comment]
Bedankt, ik ga dit issue sluiten
