### ISSUE TITLE
Result details op ATP niet in overeenstemming met Postman

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#293]
# Bug

Als ik het script zelf run in Postman krijg ik andere resultaten dan op het ATP:

![afbeelding](https://user-images.githubusercontent.com/37145898/65893859-04bd3e00-e3a9-11e9-96b0-d5dea0646464.png)

**Comment by stevenbal** [comment]
Dit komt doordat de gepubliceerde versie van de Postman collectie is een nieuwere versie dan de postman collectie op het test platform, omdat de gepubliceerde versie automatisch aangepast wordt als ik lokaal veranderingen maak in Postman.

Ik zal kijken of ik de gepubliceerde versie vast kan zetten, zodat hij niet automatisch geupdate wordt, maar ik vrees dat dat niet kan

**Comment by stevenbal** [comment]
Er zat een fout in de nieuwere versie van de OAS tests, ik heb het als het goed is gefixed en heb de nieuwe versie ook op api-test.nl gezet

**Comment by stevenbal** [comment]
@HenriKorver ik heb een tag toegevoegd aan de gepubliceerde postman collectie (voor de release candidate van de ZGW api's), dus als er nu updates gedaan worden op de Postman collectie, dan kan ik de tag toevoegen, de vernieuwde collectie en de url op de api-test.nl ook updaten

**Comment by alextreme** [comment]
Besproken. Vanwege de noodzaak om beide collections (op het ATP en op getpostman.com) in sync te houden is het wenselijk om te documenteren hoe de ATP postman collection opgesteld moet worden, en hoe de Postman getpostman.com beschrijving bijgewerkt dient te worden. Mag in het Nederlands.

**Comment by stevenbal** [comment]
onder https://github.com/VNG-Realisatie/api-test-platform/tree/master/doc/beheer staat beschreven hoe de gepubliceerde postman collections beheerd kunnen worden

**Comment by alextreme** [comment]
Lijkt me een nette stappenplan.

@HenriKorver wees vrij om het te doorlopen. Ik kan het me goed voorstellen dat hiernaar wordt gerefereerd wanneer we met een uitgebreidere stappenplan komen hoe derden Postman collections dienen op te stellen en op het ATP kunnen plaatsen.

**Comment by HenriKorver** [comment]
Ziet er goed uit!
