### ISSUE TITLE
Exports van testscripts naar Postman zijn niet in overeenstemming

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#294]
# Bug

Er zijn verschillende plekken binnen een test scenario van een provider run waar je een download / export kunt doen van het testscript. Helaas zijn dit vaak verschillende versies van de Postman collection

**Comment by stevenbal** [comment]
Welke plekken bedoel je precies? De download knoppen op de provider run detail pagina (https://api-test.nl/server/104d4ac1-ad07-49e0-a756-f10f08cb57a4/) en de test scenario detail pagina (https://api-test.nl/server/testscenario/5/) wijzen naar dezelfde url.

**Comment by alextreme** [comment]
Verschillende plekken zijn: via download link, of via het gepubliceerde link. 

Zelfde probleem als #293, daarom sluiten we deze issue
