### ISSUE TITLE
Consumer sessions werken niet op test en staging

### ISSUE THREAD

**Issue by stevenbal** [VNG-Realisatie/api-test-platform#298]
# Bug

Op productie werken consumer sessions wel, maar op staging.api-test.nl krijg ik de volgende response als ik een call doe naar een exposed url:

```json
{
    "info": "The requested resource has been already turned off."
}
```

en op test.api-test.nl wordt de exposed url nog steeds opgebouwd als *-test.maykin.nl

**Comment by stevenbal** [comment]
Het komt doordat alles nu geresolved wordt onder de productie omgeving, dus als ik een request doe naar `https://f5174056-ab11-449c-b13c-59eb4f7a6768-test.api-test.nl/`, dan wordt er in productie gezocht voor een `ExposedUrl` met subdomain `f5174056-ab11-449c-b13c-59eb4f7a6768-test`, terwijl er in test gezocht zou moeten worden naar subdomain `f5174056-ab11-449c-b13c-59eb4f7a6768`.

Ik ga kijken hoe ik de urlconf voor de proxy zo kan aanpassen dat dit probleem verholpen wordt

**Comment by alextreme** [comment]
Op te maken met Henri. Het is de vraag of Hostnet het mogelijk maakt dat we *test.api-test.nl en *staging.api-test.nl kunnen doorsturen naar Aleid in plaats van Alice.

**Comment by alextreme** [comment]
![Screenshot_2019-11-21_16-04-04](https://user-images.githubusercontent.com/226839/69349740-96924a80-0c78-11ea-8526-49d384c10a40.png)

**Comment by alextreme** [comment]
Besproken. Vanwege deze beperking bij Hostnet zijn consumer sessies niet goed te testen op test/staging.

Dit is gekomen vanwege het verhuizen van deze subdomeinen van maykin.nl naar api-test.nl

Opties:
- Gebruik maken van de oude test/staging domeinnamen voor de consumer sessies (123-vng-test.maykin.nl), hiervoor zouden we ons DNS moeten aanpassen en de wildcard op alice installeren
- Een apart subdomein wildcard registreren, bijvoorbeeld *.test.api-test.nl (als dit wel in Hostnet te gebruiken is)
- Zo laten (consumer sessies zijn vanuit Henri van minder belang, en op productie werkt het wel)
- Contact opnemen met Hostnet hierover 

@HenriKorver heb jij hier voorkeur in?

**Comment by HenriKorver** [comment]
Optie 3, zo laten.
