### ISSUE TITLE
Als gebruiker van het API testplatform wil ik een docker kunnen aanleveren waarop mijn provider run wordt uitgevoerd

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#301]
...zodat ik zonder mijn API te hosten kan controleren of mijn provider werkt zoals verwacht.

**Toelichting**:
Momenteel hebben we voor de client runs de mogelijkheid om een Docker of ZGW K8s-cluster op te starten, echter voor de provider runs vereisen we een publiekelijke beschikbare URL.

@HenriKorver heeft een verzoek gekregen om ook voor de provider runs (in plaats van tegen een publieke URL) een docker op te starten. Hiervoor hebben we natuurlijk in het ATP al flink wat tooling voor en een GCP integratie voor staan.

Het aan kunnen leveren van Docker images voor het testen van providers maakt het voor de gebruiker zeker een stuk eenvoudiger, echter de enige manier waarop dit handig te doen is (denk ik) is dat de gebruiker een willekeurige Docker image kan aanleveren of naar een openbare container registry zoals Docker Hub. Een image ongecontroleerd uitvoeren heeft serieuze beveiligingsgevolgen.

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by HenriKorver** [comment]
Dit lijkt een beetje op app-store-achtige functionaliteit. Ik zal @ehotting vragen om hier zijn beelden bij te geven
