### ISSUE TITLE
PDF optie bij Provider runs onzichtbaar maken

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#302]
Wens van @HenriKorver om de links naar de PDFs voor nu te verbergen, dit o.a. vanwege #300

**Comment by stevenbal** [comment]
Ik heb de PDF link verborgen in de provider run detail pagina
![Screenshot from 2019-10-21 09-43-42](https://user-images.githubusercontent.com/29249171/67185968-4f9a0680-f3e7-11e9-873a-8d687ce844bd.png)
https://test.api-test.nl/server/aac2da98-d85a-4ea2-b0ca-49674f9f6362/

En ook bij consumer sessions:
![Screenshot from 2019-10-21 09-41-52](https://user-images.githubusercontent.com/29249171/67185889-1eb9d180-f3e7-11e9-87bf-882967060a0c.png)
https://test.api-test.nl/consumer/d26404b2-5736-4297-8ccb-3982dd05fb45/

**Comment by stevenbal** [comment]
bewijs op staging:
https://staging.api-test.nl/server/adeda0f9-fdbe-4176-97b8-f86b909c5a89/
https://staging.api-test.nl/consumer/7c9532f8-17d9-457d-8704-70053be4101c/
