### ISSUE TITLE
Javascript wordt niet geladen op test, staging en productie

### ISSUE THREAD

**Issue by stevenbal** [VNG-Realisatie/api-test-platform#303]
# Bug

Het script onder `/atvstatic/js/vng.js` bestaat niet op de nieuwe servers, hierdoor werken bepaalde dingen zoals de statusbar bij het runnen van provider tests en dropdown menus ook niet

![Screenshot from 2019-10-17 10-44-23](https://user-images.githubusercontent.com/29249171/66993038-303f6880-f0cb-11e9-9069-87fae0790821.png)

**Comment by stevenbal** [comment]
Werkt inmiddels weer op test, zal met de volgende deploys naar staging en productie ook meegenomen worden

![Screenshot from 2019-10-17 11-35-35](https://user-images.githubusercontent.com/29249171/66997210-53b9e180-f0d2-11e9-917d-9f6891e01ce6.png)

**Comment by alextreme** [comment]
Deze lijkt me inmiddels achterhaald, mag je sluiten indien dat inderdaad het geval is
