### ISSUE TITLE
Shield.io caching - Badges verversen niet snel

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#305]
# Taak

Het is nog altijd zo dat de badges 5 minuten achter kunnen lopen, dit is een restrictie van shields.io om de druk op hun servers te beperken.

Aantal opties als we de badges actueler willen hebben:
- Zelf badges genereren (met Python code / Pillow?)
- Een eigen shields.io opzetten zonder de 5-minuten restrictie (hierover hebben ze documentatie voor op hun Github, node.js of docker install is mogelijk): https://github.com/badges/shields
- ?

**Comment by alextreme** [comment]
Besproken. Inrichting van shields.api-test.nl is vooralsnog voldoende (geen aparte shields-test.api-test.nl nodig).
Na inrichting op Alice/prod kunnen de test/staging omgevingen hieraan gekoppeld worden.

**Comment by stevenbal** [comment]
test gebruikt nu de badges van shields.api-test.nl, zoals te zien bij de snippets: https://test.api-test.nl/server/1/e9c534a9-7a3a-4d7e-84c5-5e0d35b211e0/

**Comment by alextreme** [comment]
@stevenbal prima, dit werkt zoals verwacht. 
Ik kan alleen niet bevestigen of dit het caching-probleem daadwerkelijk oplost (ik heb er alleen een enkele keer last van gehad).

**Comment by alextreme** [comment]
Gereed op staging, @stevenbal neemt dit mee in de productie update.

Aan @HenriKorver om aan te geven of hij het caching-probleem via de eigen shields.api-test.nl daarna nog tegenkomt.

**Comment by alextreme** [comment]
Staat op productie
