### ISSUE TITLE
Als gebruiker wil ik graag een copy button voor het kopiëren van de Markdown en HTML snippets

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#309]
Kleine moeite groot plezier

**Comment by alextreme** [comment]
Getest op staging, werkt zo te zien zoals verwacht:
![Screenshot_2019-10-28_13-14-02](https://user-images.githubusercontent.com/226839/67677658-e2f1af80-f984-11e9-9da7-529e91b44e41.png)
