### ISSUE TITLE
Logfiles werken niet meer?

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#310]
# Taak

Wellicht gerelateerd aan de Haven install (al kan ik mij herinneren dat dit ook een probleem was op rachel): het loggen van loglevels info/warning/errors lijkt niet meer in de logfiles terecht te komen. Alleen exceptions.

Dit kan nog wel tricky zijn dus wellicht handig om iemand anders erbij te pakken, ik kwam er zo snel niet uit vandaag.

**Comment by stevenbal** [comment]
Het lijkt niet te liggen aan de logging zelf, want als ik probeer te loggen op test bij bijv. de view van de lijst met consumer sessies, dan komen dat braaf in de logs terecht. Dus het lijkt erop dat er bij het maken van de call naar de proxy de code die daar bij hoort in test helemaal niet aangeroepen wordt.
