### ISSUE TITLE
Als PO wil ik een extra autorisatie-niveau voor derden

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#312]
zodat zij zelf testscripts kunnen uploaden en configureren

**Toelichting**:
Nu zijn API beheerders die gebruik willen maken van het API Testplatform afhankelijk van de admins van VNG Realisatie om een testomgeving aan te maken voor hun API('s). Het is de bedoeling dat ze dat zelf kunnen doen.

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by stevenbal** [comment]
De aanpassingen voor delete/update/create van test scenario's op API niveau zijn doorgevoerd naar test.api-test.nl. Ik heb ook een group gemaakt als voorbeeld voor beheerders van de ATP API

**Comment by stevenbal** [comment]
@alextreme zo te zien ben ik vergeten om een data migratie te doen voor het FIlefield met de postman test file, dus die ga ik nog toevoegen zodat niet alle postman tests opnieuw geupload hoeven te worden

**Comment by alextreme** [comment]
Zo te zien is de WYSIWYG-editor nog niet actief voor de description field:

![Screenshot_2019-11-14_14-35-39](https://user-images.githubusercontent.com/226839/68861576-1d30b000-06ec-11ea-844e-e1cf3ada7a6f.png)

**Comment by alextreme** [comment]
When editting a test scenario, it's not clear that the Variables and Postman test script inline forms have an additional empty form by default at the bottom.

It might be better to not show the empty inline by default (extra=0 on the inline formset?)

![Screenshot_2019-11-14_14-37-55](https://user-images.githubusercontent.com/226839/68861894-b9f34d80-06ec-11ea-909e-8153a4ec6634.png)

**Comment by alextreme** [comment]
@HenriKorver de extra autorisatie-niveau is toegevoegd op staging, echter alleen voor de provider test scenario's.

Is het ook de bedoeling dat derden voor hun API ook de consumer instellingen (session types, endpoints, scenario cases etc) kan configureren?

**Comment by alextreme** [comment]
Besproken. Wordt beperkt tot alleen de provider APIs kunnen beheren.

**Comment by alextreme** [comment]
Besproken. Het reviewen hiervan is mogelijk op staging.

Het geven van permissies is vorige week gedemonstreerd en werkt via de 'object permissions' van de API in de admin:

https://staging.api-test.nl/admin/servervalidation/api/

Daarna krijg je per API de mogelijkheid om beheer via de frontend uit te voeren:

"Configure test scenario's" knop rechtsbovenin op bijvoorbeeld:

https://staging.api-test.nl/server/2/

Graag controle of dit functioneel werkt zoals verwacht. Ik verwacht wel dat voor overdracht naar API Beheer wel een korte handleiding nodig zal zijn zodat zij weten hoe deze permissies werken.

**Comment by HenriKorver** [comment]
@alextreme Moet ik dit reviewen op staging? Ik zie namelijk dat ook al een groot deel van de functionaliteit voor het extra autorisatie-niveau uitgerold is naar productie

**Comment by HenriKorver** [comment]
Op productie zit ook zo'n "Configure test scenario's" knop, zie https://api-test.nl/server/2/

**Comment by alextreme** [comment]
@HenriKorver klopt, echter graag testen op staging voor de zekerheid.

**Comment by HenriKorver** [comment]
Lijkt allemaal goed te werken, waarvoor dank! Nog een klein puntje:

Gebruikers die geen super-user rechten hebben voor admin kunnen zelf geen API's toevoegen. Echter dit wordt wel gesuggereerd in de object-permissies

![afbeelding](https://user-images.githubusercontent.com/37145898/69972288-a552ea00-1521-11ea-9956-3db4c7b2f915.png)

https://staging.api-test.nl/admin/servervalidation/api/2/permissions/
