### ISSUE TITLE
Als provider wil ik testruns kunnen bewerken

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/api-test-platform#314]
...zodat ik de configuratie kan aanpassen als ik fouten maak.

**Toelichting**:
Ik heb via `ZGW APIs > Provider > Start testrun` een provider test aangemaakt en een aantal URLs vergeten aan te passen. Ook zorgen de geconfigureerde secret voor server errors, wat ik door een ander secret wil aanpassen, maar dat is niet mogelijk.

**Oplossingsrichting**:

Edit knop om het formulier weer boven te halen :-)

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by alextreme** [comment]
Lijkt mij inderdaad een vrij essentiele onderdeel van het test-platform (en maakt het gebruik een stuk eenvoudiger). 

Aan @HenriKorver om aan te geven of dit onderdeel dient te worden van de volgende sprint.

**Comment by HenriKorver** [comment]
Terechte wens. Ik heb m in de sprint gezet

**Comment by alextreme** [comment]
@stevenbal wees vrij om op te pakken en voor de zekerheid te dubbelchecken met Sergei

**Comment by stevenbal** [comment]
@alextreme deze feature staat nu op test, de update knop is rechtsboven zichtbaar als de user de benodigde permissie heeft: https://test.api-test.nl/server/1/2fdcb0ab-c624-4468-8aa9-787fae0d6ba9/06404121-75c7-459d-a01f-aecce724a495/

**Comment by alextreme** [comment]
@stevenbal 
- zou je nog iets anders met die 'reset' knop kunnen doen? 'cancel' lijkt mij logischer in deze context. 
- 'Modify environment' voor de knop naar dit scherm lijkt mij een betere term dan 'update environment'. 

Verder prima.

**Comment by stevenbal** [comment]
@alextreme de reset knop zet alle variabelen die aangepast zijn in de form terug naar de originele waarde, of heb je liever een knop die je terug brengt naar de vorige pagina?

**Comment by alextreme** [comment]
@stevenbal het terug gaan naar de vorige pagina (afbreken van de edit) zou ik in dit geval eerder verwachten dan het terugzetten naar de originele waarden.

**Comment by stevenbal** [comment]
@alextreme ik heb het aangepast, staat nu op test

**Comment by alextreme** [comment]
@stevenbal Prima. Wees vrij om door te zetten naar staging.

**Comment by alextreme** [comment]
@HenriKorver de mogelijkheid om de environments te wijzigen zit inmiddels op staging en je hebt aangegeven om op productie te willen checken.

@stevenbal zie PR 254, we zitten nog wel met een merge conflict tussen staging en master.

**Comment by stevenbal** [comment]
@HenriKorver deze feature zit nu op productie

**Comment by HenriKorver** [comment]
Het lijkt nog niet helemaal goed te gaan, zie https://api-test.nl/server/2/66572b52-2e64-434b-8024-0d2cd3455543/

De variabele demo-url (https://demo.api-test.nl/api/v2 ) op de detailpagina is nog niet aangepast aan de waarde van de aangepaste environment (https://demo.api-test.nl/api/v3).

De badge op de detailpagina is groen, hoewel de test in deze aangepaste environment nog nooit is geslaagd.  Het lijkt niet handig te zijn om zomaar een environment te kunnen aanpassen.
Dus als een bestaande environment niet goed is ingevuld is het beter om de hele combinatie van testscenario en environment te verwijderen en een nieuwe aan te maken. Anders krijg je dit soort rare randeffecten die lijken op geschiedenisvervalsing.
Het is wel handig om een dupliceer-button te hebben (of iets dergelijks) zodat je niet alle omgevingsvariabelen opnieuw hoeft in te tikken.

**Comment by alextreme** [comment]
Goed punt.

Het bij het aanpassen van de environment-variabelen automatisch verwijderen van de eerdere runs met de oude instellingen lijkt mij in dit geval het meest wenselijk: door het aanpassen van de variabelen 'invalidate' je de eerdere runs.

**Comment by stevenbal** [comment]
@alextreme Ik liep nog tegen een bug aan op productie, waardoor soms de volgorde van de endpoints overhoop gegooid wordt na het updaten van waardes
![Screenshot from 2019-11-29 12-44-48](https://user-images.githubusercontent.com/29249171/69867247-8dbbfd00-12a6-11ea-8684-d7fa4060aa15.png)
Na een update
![Screenshot from 2019-11-29 12-46-50](https://user-images.githubusercontent.com/29249171/69867252-8f85c080-12a6-11ea-8836-b64a42ff856e.png)

Ik zal het fixen

**Comment by stevenbal** [comment]
Fix voor de ordening van de placeholders is doorgevoerd op staging @alextreme

**Comment by alextreme** [comment]
Wijzigen van bestaande environments kan getest worden op staging. Bij mij werkt dit nu zoals verwacht, wel is nog een authorisatie-probleem met mijn ZGW tokens maar dat is onderdeel van #238 en is gemeld aan Sergei
