### ISSUE TITLE
Als gebruiker wil ik een buildnummer (hash/versie) van mijn software kunnen meegeven aan een testrun

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#316]

**Comment by alextreme** [comment]
Een mogelijke oplossing hiervoor zou het via de API van het ATP instellen van de suppler information zijn, en het uitbreiden van deze informatie met een versienummer van het systeem van de leverancier:

https://api-test.nl/server/2/dff1f823-ecc7-4ab8-8fb6-cc20793bd60f/3fa51402-62c6-42d6-89fd-e14a2b818a6c/latest/

![Screenshot_2019-11-14_15-53-09](https://user-images.githubusercontent.com/226839/68867963-f4fa7e80-06f6-11ea-8553-f98ec5ee8df2.png)

Ik heb nog niet uitgezocht of dit wel of niet al onderdeel is van de API.

**Comment by stevenbal** [comment]
Staat nu op staging, het is nu mogelijk om per provider run aan te geven welke versie van het product het om ging
https://staging.api-test.nl/server/1/d2b890ca-dfe2-4c4e-b2d7-3893e881c579/

![Screenshot from 2019-12-02 14-58-12](https://user-images.githubusercontent.com/29249171/69965281-3753f600-1514-11ea-8e0c-bb473025d116.png)

**Comment by JanWillemKooi** [comment]
Conclusie: Software version wordt build version en kan op run niveau aangepast worden.

**Comment by stevenbal** [comment]
Veld is nu hernoemd naar `build_version` in https://github.com/VNG-Realisatie/api-test-platform-code/commit/5deb47e08ef5922a2c6f06129ea50032d016f6ea

**Comment by alextreme** [comment]
@stevenbal je mag nog even kijken naar de tabel van deze variabelen op de provider-test / scenario-niveau:

https://staging.api-test.nl/server/1/66fd6000-2bb2-453c-8ea0-fd7109c07026/f111dde2-346e-41b9-bb39-fe89fd362942/

De tabel over de volledige breedte weergeven vind ik vreemd ogen, het gaat om meta-data wat prima rechts in de hoek geplaatst kan worden zodat het niet afleidt van de mooie groene vinkjes daaronder:

![Screenshot_2019-12-05_17-23-26](https://user-images.githubusercontent.com/226839/70254210-02020f00-1785-11ea-9bfd-04dbe094bd14.png)

**Comment by stevenbal** [comment]
@alextreme staat inmiddels op staging:
https://staging.api-test.nl/server/1/66fd6000-2bb2-453c-8ea0-fd7109c07026/f111dde2-346e-41b9-bb39-fe89fd362942/
![Screenshot from 2019-12-09 14-22-23](https://user-images.githubusercontent.com/29249171/70439015-5d871200-1a8f-11ea-9ac0-3716ce224233.png)

**Comment by alextreme** [comment]
@stevenbal dank, maar kan je hem niet wat smaller maken? Kijk eens naar het 'Supplier information' tabelletje op de detail-weergave, daar staat het wat dichter bij elkaar en is het duidelijk dat ze bij elkaar horen.

**Comment by stevenbal** [comment]
@alextreme zoiets?
![Screenshot from 2019-12-09 16-06-25](https://user-images.githubusercontent.com/29249171/70446861-09375e80-1a9e-11ea-81f2-976ab6f3235b.png)

**Comment by alextreme** [comment]
Yes stukken beter. Sorry voor het pingpongen.

**Comment by stevenbal** [comment]
@alextreme staat weer op staging

**Comment by alextreme** [comment]
@HenriKorver wees vrij om aan te geven of het wijzigen van de environment so voor je werkt, ter voorbeeld:

https://staging.api-test.nl/server/1/66fd6000-2bb2-453c-8ea0-fd7109c07026/f111dde2-346e-41b9-bb39-fe89fd362942/
