### ISSUE TITLE
Als PO wil ik een testscript voor BRK Bevragingen (Haal Centraal)

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#320]
10 dec ga ik naar API Lab BRK Bevragingen (Haal Centraal). Het zou fijn zijn als Steven die dag stand-by kan zijn (in Amsterdam) zodat we een die dag een testscriptje kunnen maken voor deze API. Het betreft vooral de happy flow van de OAS.

**Comment by alextreme** [comment]
@HenriKorver of @JanWillemKooi mogen hiervoor URLs, documentatie en API keys aanleveren. Steven zal dinsdag 10 dec standby staan maar alvast wat voor kunnen bereiden is wenselijk.

**Comment by HenriKorver** [comment]
https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen

https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen

**Comment by HenriKorver** [comment]
De (referentie-)implementaties voor deze API's zijn volgens mij nu nog niet beschikbaar. Ik heb Brenda gevraagd en wacht nog op haar antwoord. Misschien weet @JanWillemKooi meer.

**Comment by JanWillemKooi** [comment]
De API's zijn pas op 10 dec algemeen beschikbaar. Voor mensen die al eerder een API-key voor bijvoorbeeld de BRP hebben gehad, kunnen die nog steeds gebruiken. Maar het plan is om op 10 dec 1 algemene API-key te hebben. (in elk geval voor BRK)

**Comment by stevenbal** [comment]
@HenriKorver ik heb alvast een simpel testscenario gemaakt ervoor https://api-test.nl/server/6/testscenario/16/, op 10 december zal ik testen of er geen fouten in het scriptje zitten

**Comment by HenriKorver** [comment]
Dank voor deze proactiviteit!
