### ISSUE TITLE
Supplier information kan onterecht per run worden aangepast

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#325]
# Bug
Supplier information kan nu per run worden aangepast. Je zou zeggen dat je de supplier information slechts op environment-niveau zou mogen wijzigen.

**Comment by alextreme** [comment]
Toevallig is dit een aanpassing dat @stevenbal al binnen een andere issue heeft verholpen. Ik weet nog niet of dit al op staging staat maar ik heb zijn wijzigingen goedgekeurd.

**Comment by stevenbal** [comment]
Op staging kan de supplier informatie nu alleen op environment niveau aangepast worden:
https://staging.api-test.nl/server/2/059e9c61-e832-48af-8ad1-5b2bcc312b6b/09d84481-a1a0-4581-8002-1209d85bf97b/
![Screenshot from 2019-12-03 10-01-05](https://user-images.githubusercontent.com/29249171/70035817-e5fb4380-15b3-11ea-9976-c6bf993b3d2d.png)

Deze informatie is ook nog weergegeven bij de individuele runs voor dat environment:
https://staging.api-test.nl/server/2/9c4a95c3-3166-43fa-8448-298cd7b0fac6/
![Screenshot from 2019-12-03 10-01-02](https://user-images.githubusercontent.com/29249171/70035833-ee537e80-15b3-11ea-8579-2171efb749c8.png)

En daar kan alleen de software version aangepast worden. Ik dacht dat het wel handig zou zijn om de supplier informatie ook op de detail pagina's weer te geven, maar ik kan ze beter loshalen van elkaar denk ik, dus een apart tabelletje voor de supplier informatie van het environment, en een andere voor de software versie @HenriKorver

**Comment by HenriKorver** [comment]
Ik begrijp niet waarom er onderscheid wordt gemaakt voor het veld "software version". Volgens mij wil je dat veld ook niet per rum kunnen aanpassen. Een nieuwe software versie betekent in mijn ogen een nieuwe environment

**Comment by stevenbal** [comment]
Dat is gedaan naar aanleiding van deze https://github.com/VNG-Realisatie/api-test-platform/issues/316 user story. Het is nu ook zo dat de referentieimplementatie geupdate wordt, maar met hetzelfde environment getest wordt toch?

**Comment by HenriKorver** [comment]
Ja je hebt gelijk. Alleen bij een major software update waarbij ook de URL van de API veranderd zal je een nieuwe environment moeten aanmaken, maar dat gaat vanzelf goed.

**Comment by HenriKorver** [comment]
> Ik dacht dat het wel handig zou zijn om de supplier informatie ook op de detail pagina's weer te geven, maar ik kan ze beter loshalen van elkaar denk ik, dus een apart tabelletje voor de supplier informatie van het environment, en een andere voor de software versie 

Zo als het nu is vind ik eigenlijk wel prima. Dus gewoon alle supplier gegevens bij elkaar houden inclusief software version en ervoor zorgen dat je per run alleen de software version kunt aanpassen.

**Comment by alextreme** [comment]
Ter controle door @HenriKorver op staging, wel nog met een opmerking van mijn kant over de UI maar die kan Steven oppakken in #316

**Comment by HenriKorver** [comment]
Als je op run-niveau de "software version" wilt aanpassen krijg je in het update scherm de term "build version". Graag op alle plekken dezelfde naam gebruiken voor hetzelfde veld. Anders kan het leiden tot verwarring.
