### ISSUE TITLE
Standaard inklappen environment variabelen op detail-weergave run

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#326]
# Taak

https://api-test.nl/server/1/daebab35-8abe-42b3-b5de-c93a45c1f1c2/

![Screenshot_2019-12-05_15-15-40](https://user-images.githubusercontent.com/226839/70243195-69fb2a00-1772-11ea-8912-6e8a1715db5f.png)

Juist de resultaten van de test-run zijn het interessants (het tabelletje "Postman collection #1 results details") en de lange lijst van ZGW environment variabelen duwt deze resultaten ver naar beneden. 

Dus van mij mag alles wat onderdeel is van de environment in een aparte tabel worden gezet en standaard inklappen. En dan dat je de environment variabelen met een knopje zichtbaar kan maken.

@HenriKorver wees vrij om in de sprint te slepen als je het hiermee eens bent.

**Comment by stevenbal** [comment]
Bij deze een aparte tabel voor de environment variabelen, by default ingeklapt
![Screenshot from 2019-12-16 15-04-52](https://user-images.githubusercontent.com/29249171/70913027-7f474280-2015-11ea-9244-51bf851d393f.png)
![Screenshot from 2019-12-16 15-04-55](https://user-images.githubusercontent.com/29249171/70913030-80786f80-2015-11ea-8df7-f4a15a4cb9f5.png)

@alextreme linkje voor staging: https://staging.api-test.nl/server/1/38bbcbf1-f6c3-4986-ac0f-3c28f9c1750f/

**Comment by alextreme** [comment]
Is in orde, wel langs @HenriKorver aangezien hij zich anders kan afvragen waar zijn environment variabelen zijn gebleven.

**Comment by alextreme** [comment]
![Screenshot_2019-12-20_16-22-25](https://user-images.githubusercontent.com/226839/71264698-f4cc4f00-2344-11ea-8ba5-97fcb0737356.png)
