### ISSUE TITLE
BRK run met ongeldige API key - alle requests geven een 400 error maar run geeft groene badge

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#330]
# Taak

Er zitten hier geen assertions in, dus een groene uitslag is logisch. Echter er zijn wel 9 falende tests in het HTML rapport.

Dus de vraag is hier of we niet te losjes omgaan met falende requests zonder assertions:

https://api-test.nl/server/6/efa304e9-1395-43f2-b36e-102c1f697f99/

![Screenshot_2019-12-12_15-28-37](https://user-images.githubusercontent.com/226839/70720541-42690c00-1cf4-11ea-9cda-5451cbf9fc7f.png)

![Screenshot_2019-12-12_15-28-49](https://user-images.githubusercontent.com/226839/70720545-4563fc80-1cf4-11ea-9cf5-d62bb6cbe395.png)

**Comment by stevenbal** [comment]
Deze provider run wordt nu zoals verwacht aangegeven als gefaald:
https://api-test.nl/server/6/efa304e9-1395-43f2-b36e-102c1f697f99/

**Comment by alextreme** [comment]
Yes, deze output voor de BRK tests is nu conform verwachting:

![Screenshot_2019-12-20_15-54-18](https://user-images.githubusercontent.com/226839/71262885-07448980-2341-11ea-86fa-537932b3d2f2.png)
