### ISSUE TITLE
Als PO wil ik de twee testscripts voor ZGW API's samenvoegen tot één samengesteld testscenario

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#331]
Momenteel hebben we twee testscripts om de ZGW API's te testen:
- één voor het testen van de OAS spec
- één voor het testen van het gewenste gedrag van de API conform de eisen in de standaard.md beschrijving

Het doel is om deze samen te voegen zodat beide scripts in één run kunnen worden uitgevoerd en het resultaat in één rapport met één badge kan worden gepubliceerd.

**Comment by HenriKorver** [comment]
In de detailpagina zou dit moeten resulteren in twee afzonderlijke links naar de Newman reports

**Comment by stevenbal** [comment]
Bij deze het testscenario met beide testsuites:
https://api-test.nl/server/1/testscenario/19/

en een voorbeeld van een provider run voor dit scenario:
https://api-test.nl/server/1/e3ccea18-ac67-43e1-86a0-2a9d7a41b316/

**Comment by stevenbal** [comment]
Het testscenario is voor het eerst geslaagd :confetti_ball: 
https://api-test.nl/server/1/aecc861f-9828-4f4c-aa00-92089774fda2/

**Comment by alextreme** [comment]
Dit is geslaagd bij een eerdere run. Wel nu af en toe falend vanwege het '502 Bad Gateway' probleem.

**Comment by HenriKorver** [comment]
Het gecombineerde script heeft al een paar nachten gerund met succes. Dus ik kan deze US met een gerust hart afsluiten
