### ISSUE TITLE
Bijwerken tutorials voor provider tests/consumer sessies in GitHub

### ISSUE THREAD

**Issue by stevenbal** [VNG-Realisatie/api-test-platform#333]
# Taak

Aangezien er aardig wat veranderd is aan zowel het web interface als de backend (environments voor provider runs, API's in het menu etc.), is het misschien een goed idee om de tutorials op de github voor [provider testing](https://github.com/VNG-Realisatie/api-test-platform/blob/master/tutorials/PROVIDER_TEST.md) en [consumer sessies](https://github.com/VNG-Realisatie/api-test-platform/blob/master/tutorials/CONSUMER_SESSION.md) te updaten waar nodig.

**Comment by stevenbal** [comment]
@HenriKorver @alextreme kan ik deze in de sprint slepen?

**Comment by HenriKorver** [comment]
Prima plan!

**Comment by HenriKorver** [comment]
Dank voor de aanpassingen
