### ISSUE TITLE
Newman out of memory error bij runnen ZGW standaard tests

### ISSUE THREAD

**Issue by stevenbal** [VNG-Realisatie/api-test-platform#337]
# Bug

https://api-test.nl/server/1/6b5fe675-694d-4948-8896-5eae88d30ef0/97fa6f1e-33df-4248-b6ed-125f6f8e559f/

Bij het runnen van grote testcollecties (zoals de ZGW api tests) geeft Newman soms een out of memory error

**Comment by alextreme** [comment]
@stevenbal wat denk je van het opknippen van deze tests in 2 of meer losse PM collections? Zo te zien heeft het te maken met het genereren van het rapport.

**Comment by stevenbal** [comment]
@alextreme dat kan, alleen dan moeten die losse PM collections wel apart gepubliceerd worden (en ook apart opgehaald en gerund worden voor openzaak, terwijl een grote collection daarvoor makkelijker is)

**Comment by alextreme** [comment]
Okay, probeer het dan maar eerst met de voorgestelde verhoging.

**Comment by stevenbal** [comment]
lijkt te werken, zal hem nog een paar keer runnen voor de zekerheid
https://api-test.nl/server/1/6b5fe675-694d-4948-8896-5eae88d30ef0/306338e9-b9e4-48be-8e5a-bd3792f24c74/

**Comment by alextreme** [comment]
:v: 
![Screenshot_2019-12-20_11-28-07](https://user-images.githubusercontent.com/226839/71248707-d1d97500-231b-11ea-8a50-39c93a0645b9.png)
