### ISSUE TITLE
Collection van calls opstellen voor MOR test-client voorbeeld uit US #36

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#38]
In user story #36 is een voorbeeld scenario op basis van een MOR test-client beschreven.

Dit dient uitgewerkt te worden in een Postman collection waarmee deze test-client wordt gesimuleerd.

Voor nu dient dit rechtstreeks op de ZDS 2.0 componenten aangesloten te zijn.

**Comment by alextreme** [comment]
Een eerste opzet:

https://github.com/VNG-Realisatie/api-testvoorziening/blob/master/MOR%20test-client.postman_collection.json

**Comment by alextreme** [comment]
[MOR test-client.postman_collection.json.txt](https://github.com/VNG-Realisatie/api-testvoorziening/files/2653269/MOR.test-client.postman_collection.json.txt)

**Comment by alextreme** [comment]
Zie uiteindelijke Postman collection hier:

https://github.com/maykinmedia/api-testvoorziening/tree/master/postman_collection

**Comment by alextreme** [comment]
@HenriKorver deze mag je reviewen

**Comment by HenriKorver** [comment]
@alextreme Als ik een testsessie opstart via postman, zie ik hem niet verschijnen in het user-interface.

**Comment by alextreme** [comment]
Dank voor het aanpassen. Als je je collection toevoegt aan deze issue dan vervang ik 'm.

De /api/v1/henri die ik had toegevoegd via de admin gisteren zat nog als verplichte GET-call in de scenario cases. Bij deze is het verwijderd, probeer het maar nog een keer. Je kan de cases hier aanpassen als je dat wilt: https://vng-staging.maykin.nl/admin/testsession/scenariocase/

De UI laat alleen jouw eigen sessies zien. Kijk even met welke user de test-session wordt aangemaakt door Postman, je kan via de admin wisselen van gebruiker door iemand te 'hijacken': https://vng-staging.maykin.nl/admin/accounts/user/

**Comment by HenriKorver** [comment]
Zie hier voor de aangepaste collectie:
https://github.com/VNG-Realisatie/api-testvoorziening/blob/master/MOR%20test-client%20vng-staging.postman_collection.json
