### ISSUE TITLE
Genereren rapport op basis van voorbeeld #40, US #36

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#41]
Taak bij US #36 
Dit zou een PDF, HTML of een online/real-time rapport kunnen zijn. Nader te bepalen

**Comment by HenriKorver** [comment]
@alextreme In onderstaand rapportje graag nog de volgende verbeteringen:
* Scenario vervangen door Endpoint als titel van tweede kolom.
* In geval status code negatief is (400, 500, etc.) mag het resultaat niet Succesvol zijn (groen blokje) maar moet het Gefaald zijn (rood blokje).
* De combinatie Http-method met Endpoint (voorheen Scenario) mag maar één keer voorkomen in het rapport. Indien dezelfde combinatie meerdere keren voorkomt in een sessie dan moet de desbetreffende call elke keer geslaagd zijn om te resulteren in een groen blokje (Succesvol). Als de call één keer mislukt dan is het resultaat altijd een rood blokje (Gefaald).

![image](https://user-images.githubusercontent.com/37145898/51388357-71e5b780-1b29-11e9-858b-55392506f3ed.png)

**Comment by alextreme** [comment]
Dank voor het melden, ik heb dit aan onze kant (Taiga #136) uitgesplitst.

**Comment by HenriKorver** [comment]
Er zijn ook nog paar dingetjes rondom de STOP button.
* Als ik deze button indruk, dan wordt de testsessie niet gestopt. Ik kan nog steeds requests uitvoeren die keurig door de TV worden gelogd.
* Na het indrukken van de STOP button verandert deze in een "DCR Data test report" button. Waarom heet deze DCR? En wat is de toegevoegde waarde van het onderliggende PDF-rapport dat er niet weer iets anders uitziet dan de andere PDF-rapporten?
