### ISSUE TITLE
Provider testen, resultaten aanroepbaar met API (US #37)

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#48]
# Taak

Als je een Postman collectie gedraaid heb op de test-omgeving, dan wil je de resultaten programmatisch (via een API) ophalen:

1) authenticatie
2) starten provider test (welke Postman collectie, met 1 of meerdere URLs van de providers en de JWT token)
3) resultaten van deze aanroep terugkrijgen (zowel goede als slechte resultaten)

@HenriKorver bedenkt of dit synchroon of asynchroon hoort te verlopen

[assign aan teamlid]

**Comment by alextreme** [comment]
Dit is inmiddels volledig mogelijk, we misten nog een 'result' action. Bijgesloten postman collection geeft aan hoe je de stappen kunt uitvoeren en ik heb een voorbeeld bijgesloten van de output van de resultaten.

Het idee voor het starten van de provider-run is dat je de body als volgt formatteert:

POST https://vng-staging.maykin.nl/api/v1/provider-run/
`{
    "test_scenario": "ZDS 2.0 verification test",
    "client_id": "test",
    "secret": "testsecret",
    "endpoints": [
    	{
    		"url": "https://ref.tst.vng.cloud/drc/",
    		"test_scenario_url":{
    			"name": "DRC"
    		}
    	},
    	{
    		"url": "https://ref.tst.vng.cloud/ztc/",
    		"test_scenario_url":{
    			"name": "ZTC"
    		}
    	},
    	{
    		"url": "https://ref.tst.vng.cloud/zrc/",
    		"test_scenario_url":{
    			"name": "ZRC"
    		}
    	}
	]
}`

In de response van de POST krijg je een 'provider_id' 

Tijdens en na het runnen kun je met deze id de resultaten opvragen:

GET https://vng-staging.maykin.nl/api/v1/provider-run/53/result

De documentatie hiervoor is tevens bijgewerkt hiervoor op:
https://vng-staging.maykin.nl/api/v1/schema#operation/v1_provider-run_create


[Provider creation.postman_collection.txt](https://github.com/VNG-Realisatie/api-testvoorziening/files/2906163/Provider.creation.postman_collection.txt)
[Provider creation result example.txt](https://github.com/VNG-Realisatie/api-testvoorziening/files/2906165/Provider.creation.result.example.txt)

**Comment by HenriKorver** [comment]
Als ik de provider run vanuit Postman opstart zie ik de sessie niet verschijnen in de user interface van de testvoorziening.

**Comment by HenriKorver** [comment]
Als ik een `GET result` doe na een provider test dan krijg ik gen feedback over failures van tests binnen de Postman collection
![image](https://user-images.githubusercontent.com/37145898/53527499-6ea9f800-3ae7-11e9-815c-436cc0e58154.png)

**Comment by HenriKorver** [comment]
In de Admin kun je de verwachte status codes vastleggen:
![image](https://user-images.githubusercontent.com/37145898/53527852-538bb800-3ae8-11e9-9bca-a2ea7467dd96.png)

Echter dit lijkt mij onnodige overhead. Je zou dit moeten kunnen doen met Javascript assertions van Postman binnen de collections:

```
pm.test("Status code is 200", function () {
    pm.response.to.have.status(200);
});
```
```
pm.test("Successful POST request", function () {
    pm.expect(pm.response.code).to.be.oneOf([201,202]);
});
```

**Comment by alextreme** [comment]
> Als ik een provider test vanuit Postman opstart zie ik de sessie niet verschijnen in de user interface van de testvoorziening.

Zo te zien via de admin heb je een aantal Provider runs gestart via user 'test' ipv als user 'henri'. Dit is afhankelijk van de credentials die je gebruikt bij de eerste stap (login) in de voorbeeld collection:
![screenshot_2019-02-28_13-48-31](https://user-images.githubusercontent.com/226839/53567500-aeacc180-3b5f-11e9-817e-1bed550a3244.png)
