### ISSUE TITLE
Provider testen, andere soorten test-scripts dan Postman

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#49]
# Taak

Aan @HenriKorver om dit verder uit te zoeken qua requirements

Ingeschreven personen: Gherkin scripts ipv Postman, Cucumber

Onderzoek:
https://docs.cucumber.io/gherkin/
https://hiptest.com/docs/writing-scenarios-with-gherkin-syntax/
https://semaphoreci.com/community/tutorials/integration-testing-your-http-api-with-cucumber
https://www.agiletrailblazers.com/blog/6-reasons-to-use-postman/newman-for-api-integration-testing
https://www.npmjs.com/package/postman-bdd

[assign aan teamlid]

**Comment by HenriKorver** [comment]
Voobeelden van Gherkin scripts
https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/tree/master/features

**Comment by alextreme** [comment]
Niveau van beschrijven in Gherkin zou een stuk 'dieper' moeten zijn om een uitvoerbaar (en bruikbare) test scenario-script te kunnen realiseren:

Feature: Requesting an Insecure Resource
Scenario: Request the Insecure Resource
When I make a "GET" request to "/api/insecure"
Then I get a "200" response
And the response is:
"""
{
"answer": 42,
"name": "Graham"
}
"""

Waarde van Gherkin als functionele specificatie is groot (het is erg duidelijk beschreven en zal de realisatie van een referentiecomponent en/of een test-suite vergemakkelijken). 

Meerwaarde van het kunnen maken van een vertaalslag van Gherkin naar een uitvoerbare script (Python/Javascript) is twijfelachtig. Je bent dan een compiler vanuit natuurlijke taal naar een programmeertaal aan het ontwikkelen. Dat zal verwacht ik veel meer tijd kosten dan het los van elkaar op basis van een Gherkin specificatie opstellen van een Postman collection ter verificatie van de API.

Dus Postman en Gherkin zouden elkaar kunnen versterken, maar zouden het beste naast elkaar leven.

Optie is wel dat het test-platform een 'generieke' API test-image zou kunnen ondersteunen (op basis van Docker). Voor nu te ambiteus.

**Comment by alextreme** [comment]
https://trends.google.com/trends/explore?geo=NL&q=Postman,SOAPUI,Katalon
![screenshot_2019-01-17_15-47-34](https://user-images.githubusercontent.com/226839/51326353-3c7c9380-1a6f-11e9-9a1e-87f74b114e48.png)

**Comment by alextreme** [comment]
https://trends.google.com/trends/explore?cat=5&geo=NL&q=Postman,Cucumber,Gherkin
![screenshot_2019-01-17_15-49-30](https://user-images.githubusercontent.com/226839/51326470-82395c00-1a6f-11e9-9b77-b7fa8b1dfa5f.png)
