### ISSUE TITLE
Provider testen, Fysiek rapport als bewijs (US #37)

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#50]
# Taak

- Overzicht scenario's met vinkje
- volgens standaard STUF rapport (pag 1+2)

PDF

[assign aan teamlid]

**Comment by alextreme** [comment]
Henri zoekt of hij hiervoor een uptodate voorbeeld hebt

**Comment by HenriKorver** [comment]
@michielverhoef @melsk-r  Is bovenstaand testrapport representatief? Of weten jullie betere te vinden op de software catalogus?
https://www.softwarecatalogus.nl/pakketten/norm_version/Zaak-%20en%20documentservices%201%252E0?zoek=
Ook zou ik graag een testrapport vinden met negatieve resultaten.
Het lukt me überhaupt niet om te filteren op pakketen die een testrapport hebben. Dat maakt het lastig zoeken.

**Comment by alextreme** [comment]
@HenriKorver ik heb even gekeken naar je rapport, maar dit lijkt ('Zaakservice consumer') niet op een testrapport van een provider.

Ik weet niet of het qua structuur veel uitmaakt maar zet dan ook die van Exxellence ZDS 1.0 door die ik in de softwarecatalogus tegen kwam: https://www.softwarecatalogus.nl/pakket/exxellence-suite?version-detail=20282

**Comment by HenriKorver** [comment]
Hopelijk voldoet dit rapport beter: https://www.softwarecatalogus.nl/sites/default/files/20161011-498868-testrapportage.pdf

**Comment by michielverhoef** [comment]
Dat is een interessant rapport, er staan wat kleine vormfoutjes in zoals op pagina 8, paragraaf 3.1. De productlink moet (volgens de toelichting onder de tabel) de link zijn naar waar het product beschreven staat in de software catalogus. Nu staat er een link naar een eigen Wiki.

Dat is misschien geen reuze probleem maar om het voor iedereen makkelijker te maken zouden dat soort gegevens gegenereerd moeten worden door de testvoorziening. Wanneer ze handmatig ingevuld moeten worden kunnen dit soort oneffenheden er in sluipen.

**Comment by HenriKorver** [comment]
@michielverhoef Dank voor je observatie, we zullen opletten dat we dit wel goed doen in de api testvoorziening. Andere vraag: betreft het hier een testrapport van een zaakregistratiesysteem c.q. zakenmagazijn (service provider)? Als rol staat er "zaaksysteem". Wat is dat? Kan net zo goed een zaakafhandelingsysteem zijn...

**Comment by michielverhoef** [comment]
Dat is precies 1 van de punten waarop de ZDS 1.n niet correct aansluit op GEMMA 2 en daarmee de softwarecatalogus: ZDS 1.n is gebaseerd op de GEMMA 1 en opgebouwd volgens de bijbehorende referentiecomponenten. Het is niet mogelijk om die te plotten op GEMMA 2 componenten als Zaakregistratiecomponent en Zaakafhandelcomponent omdat een zaaksysteem zowel de rol van ZRC als Generieke ZAC heeft. Indertijd hebben we geprobeerd dit om te schrijven maar het is niet gelukt, dan moest de hele standaard opgesplitst worden en had je iets heel anders (qua verdeling kwam je dan uit op iets wat lijkt op de nieuwe ZGW API).

Een onbedoeld gevolg hiervan is dat in de software catalogus een zaaksysteem beide referentiecomponenten (ZRC en ZAC) invult maar slechts 1 testrapport toe kan voegen. Wanneer je dit testrapport niet (goed) leest kan een positief testrapport voor een consumer gezien worden als compliancy voor de provider terwijl dit niet getest hoeft te zijn.

Zo te zien moet er misschien ook maar eens kritisch naar de software catalogus gekeken worden...

**Comment by HenriKorver** [comment]
Dank voor de antwoorden! Dus dit rapport  https://www.softwarecatalogus.nl/sites/default/files/20161011-498868-testrapportage.pdf van Exxellence, wat ik al eerder noemde, betreft ook een testrapport van een provider,

**Comment by michielverhoef** [comment]
Helemaal correct! :-D
