### ISSUE TITLE
Provider testen, logging van fouten in de test-sessie (#37)

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-test-platform#51]
# Taak

Doel is dat ontwikkelaars van providers de oorzaak van fouten uit de provider test-sessie kan achterhalen

[assign aan teamlid]

**Comment by HenriKorver** [comment]
@alextreme Krijg een 500 melding als ik een PDF-rapportje aanvraag.

**Comment by alextreme** [comment]
Ik heb aan Alvise gevraagd om vng-test en vng-staging te updaten en naar de errors te kijken, we pakken ze op

**Comment by alextreme** [comment]
We hebben hiervoor een foutief voorbeeld van een test-scenario toegevoegd aan vng-staging:

"ZDS 2.0 verification test (error example)"

Dit zorgt voor de volgende details qua logging:
![screenshot_2019-02-26_16-07-46](https://user-images.githubusercontent.com/226839/53423638-01606f00-39e2-11e9-9643-55dbead2c305.png)
[Server run 52 report.pdf](https://github.com/VNG-Realisatie/api-testvoorziening/files/2906131/Server.run.52.report.pdf)
