### ISSUE TITLE
In interface staan bovenin 2 tabbladen Test Client en Test Server. Test Server wijzigen in Test Provider

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-test-platform#61]
# Bug

Niet echt bug maar wellicht eenduidiger...

[assign aan teamlid en voeg label 'bug' toe, kies bij 'projects' voor 'Scrum ZDS Realisatie Huidige Sprint']

**Comment by HenriKorver** [comment]
En Test Client veranderen in Test Consumer

**Comment by alextreme** [comment]
"Test Provider" wordt nu aangehouden. "Test Consumer" wordt nog gedaan.

**Comment by alextreme** [comment]
Bij deze doorgevoerd:

https://vng-staging.maykin.nl/

![screenshot_2019-02-20_12-44-45](https://user-images.githubusercontent.com/226839/53089609-55181780-350d-11e9-82ee-0c793e4f9303.png)
