### ISSUE TITLE
Als provider-tester wil ik een test kunnen uitvoeren (incl. starten) vanuit mijn CI/CD omgeving

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#63]
...zodat [vul aan].

**Toelichting**:
...

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by alextreme** [comment]
Ik heb aan Alvise gevraagd om de test-platform API documentatie met ReDoc (gelijk aan de ZGW-APIs) te combineren aangezien het gevraagde inmiddels wel mogelijk is, maar ik het overzicht van test-platform API calls een beetje kwijt ben.

**Comment by alextreme** [comment]
URL van de documentatie, dit is net uitgerold dus we moeten hier nog even goed doorheen maar wees vrij om mee te kijken:

https://vng-staging.maykin.nl/api/v1/schema

**Comment by alextreme** [comment]
Zie #48 voor een concreet voorbeeld met PC om dit uit te voeren.

Enige vereiste voor een CI/CD-omgeving is dat de API die getest wordt bereikbaar is vanaf het API test platform. Eventueel dus dat het API test-platform expliciet toegang gegeven moet worden door de leverancier (bijvoorbeeld door het IP te whitelisten) zodat het API test-platform bij de te testen API mag komen.
