### ISSUE TITLE
Als consumer-tester wil ik de mogelijkheid hebben om de volgorde van http calls af te dwingen en repeterende calls uit te sluiten

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#64]
zodat de consumer-applicatie strenger getest kan worden

**Toelichting**:
...

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by alextreme** [comment]
Extra optie in de admin om aan te geven dat voor een testsession-type de volgorde van de scenario-calls verplicht is.

Eveneens is wenselijk dat het makkelijk is om de volgorde van de scenario-calls in te stellen (drag & drop bijv)

**Comment by alextreme** [comment]
Extra optie in de admin om aan te geven dat voor een testsssion-type het niet toegestaan is om meerdere keren dezelfde calls uit te voeren (dus optie om: een-en-maar-eenmaal uitvoeren)
