### ISSUE TITLE
Als potentiele gebruiker van een API wil ik de ATV gebruiken als playground (speelomgeving) 

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-test-platform#86]
zodat ik snel de API kan begrijpen en beoordelen of de API nuttig is om te gebruiken.

**Toelichting**:
Naast het gebruik van de ATV als compliancy-voorziening (aantonen dat de API consumer of provider voldoet aan de standaard) is het ook nuttig om de ATV te gebruiken als een sandbox of playground om met een API te spelen.

**Oplossingsrichting**:
Biedt de mogelijkheid om via de proxy van de ATV de provider API te benaderen zonder authenticatie/autorisatie procedures. Gebruiker hoeft alleen in te loggen op de ATV en daar wordt vervolgens achter de schermen de authenticatie en autorisatie geregeld.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by HenriKorver** [comment]
Zie ook #90

**Comment by alextreme** [comment]
Bij deze is dit punt doorgevoerd op vng-staging en gecontroleerd.

Ik heb voor de Test Consumer deel een 'MOR Sessie (+auth)' aangemaakt waarbij via de admin de client ID en secret is ingevuld:

https://vng-staging.maykin.nl/admin/testsession/sessiontype/9/change/

Het starten van zo'n sessie zorgt automatisch voor een valide JWT token. Echter bij het doorklikken op de ZRC API zelf krijgen we antwoord dat er geen verplichte (andere) headers zijn bijgesloten (deze ken je wel, Accept-Crs):

![Screenshot_2019-04-12_15-27-42](https://user-images.githubusercontent.com/226839/56041057-1d249800-5d38-11e9-9ef2-047d8bccf4ed.png)

In principe is hier dus het JWT / authorisatie-deel automatisch geregeld. Echter verwacht je dat we ook automatisch andere headers injecteren zoals Accept-Crs? Het is anders nog altijd niet mogelijk om via een browser te kunnen spelen met de APIs, al maakt het het gebruik via Postman wel eenvoudiger.

**Comment by HenriKorver** [comment]
Ja, we zullen alle benodigde headers moeten injecteren om er een echte playground van te maken.

**Comment by alextreme** [comment]
@sergei-maertens kunnen we die verplichte ZGW HTTP-headers op een of andere manier negeren?

Om voor proxy-verzoeken via het test-platform on-the-fly headers zoals Accept-Crs mee te injecteren lijkt me niet echt een fijne oplossing.

**Comment by alextreme** [comment]
Assigned internally to @AlviseSembenico

**Comment by AlviseSembenico** [comment]
Feature added in https://github.com/VNG-Realisatie/api-testvoorziening/pull/126

**Comment by alextreme** [comment]
Now works as expected. I've configured the 'MOR sessie (zonder authenticatie)' with the additional Accept-Crs header, and you can now browse the API like you'd want to with a regular REST API:

https://155801121854-vng-staging.maykin.nl/zrc/api/v1/zaken

![Screenshot_2019-05-16_14-54-40](https://user-images.githubusercontent.com/226839/57855339-b8eb6d00-77ea-11e9-871d-b1df8cd29b50.png)

This is configured via the 'Inject headers' section of the Session Type admin configuration:

![Screenshot_2019-05-16_14-56-14](https://user-images.githubusercontent.com/226839/57855386-d15b8780-77ea-11e9-9023-380ef521ea15.png)

**Comment by HenriKorver** [comment]
In test session https://vng-staging.maykin.nl/882/ I have problems with authorization. This is propably caused by the new authorization model of  the ZGW API's which has been introduced recently. However it should be solved anyway.

![afbeelding](https://user-images.githubusercontent.com/37145898/58330510-4bb58880-7e37-11e9-887c-ae08c8106fd4.png)

**Comment by alextreme** [comment]
Sure, we'll refresh the Client ID's and Secret's on vng-staging.

@AlviseSembenico can you pick this up?

**Comment by alextreme** [comment]
I've tried this on staging for the 'MOR sessie (zonder authenticatie)' consumer session type, however setting the required authorizations via the webinterface didn't solve the problem.

![Screenshot_2019-05-27_12-20-01](https://user-images.githubusercontent.com/226839/58413889-2cf30400-807a-11e9-876f-72f07e6c562e.png)

@HenriKorver do the ZGW reference components work in Postman? I suspect this is broken not only for the test-platform.

**Comment by alextreme** [comment]
This is still in progress due to AC changes by Sergei

**Comment by HenriKorver** [comment]
@sergei-maertens Please give us a notification when the autorization component is fixed

**Comment by AlviseSembenico** [comment]
I move it to needs review since the functionality has been proved to run but it is hard to post image to prove it.

**Comment by HenriKorver** [comment]
It seems to be not working at all. When I start the session type "MOR sessie (zonder authenticatie)" it retuns the proxy url (https://1561382004138-vng-staging.maykin.nl/zrc/api/v1/) but the response give non-proxy urls such as https://ref.tst.vng.cloud/zrc/api/v1/zaken

![afbeelding](https://user-images.githubusercontent.com/37145898/60021824-f7e6cb00-9692-11e9-9a9b-a53e6a78d600.png)

**Comment by alextreme** [comment]
Request-rewriting seems to be working as expected however response-rewriting is indeed broken (not all of the response-data is being rewritten). Sorry Henri, this one slipped through.

@AlviseSembenico please pick this up on Wednesday, I thought we had the proxy-view sufficiently tested but it seems this still isn't the case. Or have you modified the way this is done with Sergei due to the recent ZGW changes? I know he doesn't like the ATV-responserewriting and was thinking about an alternative to deal with this.

**Comment by AlviseSembenico** [comment]
The problem was due to a missing encoding statement, that situation is handled here. https://github.com/VNG-Realisatie/api-testvoorziening-code/pull/14

**Comment by alextreme** [comment]
The bug was introduced due to conditionally deciding to rewrite the reponse based on what the server sends back. This was done in order to 'fix' the icons shown.

I've decided to remove this conditional and always rewrite the response, this is a simpler and more stable solution (even though rewriting all responses may cause problems for SVG icons)

**Comment by AlviseSembenico** [comment]
Staging update with the fixes
![image](https://user-images.githubusercontent.com/28757412/60173570-56d14f00-980f-11e9-859f-84c2c88d9f37.png)

**Comment by alextreme** [comment]
@AlviseSembenico I've had a look and the rewriting is indeed working properly now.

However when loading the ZRC ReDoc documentation I get a 500-error, while the ZTC ReDoc documentation is working as expected. Perhaps we need to extend the timeout duration?

https://1561545665151-vng-staging.maykin.nl/zrc/api/v1/schema/
![Screenshot_2019-06-26_12-44-36](https://user-images.githubusercontent.com/226839/60173979-508fa280-9810-11e9-9603-6bfbfeda1b3f.png)

**Comment by AlviseSembenico** [comment]
@alextreme I tried with the demo api and it works properly, the session that you sent is offline, which session type was it?

**Comment by alextreme** [comment]
@AlviseSembenico it was a MOR session. It seems to be working now though, so never mind.

**Comment by HenriKorver** [comment]
When I click on this url https://1561563151143-vng-staging.maykin.nl/zrc/api/v1/zaken I get a 500 message

**Comment by alextreme** [comment]
Alvise will investigate tomorrow with Sergei, however a quick look shows that the 500 is from the ZRC, all endpoints there are erroring. The ZTC is working as expected:

https://1561563151143-vng-staging.maykin.nl/ztc/api/v1/catalogussen

**Comment by alextreme** [comment]
I've updated the 'MOR sessie (zonder authenticatie)' test-session's Client ID and Secret, and I've updated the token authentication settings via: https://ref.tst.vng.cloud/tokens/set-auth/

https://vng-staging.maykin.nl/0eb97338-12f2-45cf-8f8d-59cc1f06e021/

ZRC: https://1561649037172-vng-staging.maykin.nl/zrc/api/v1/zaken

![Screenshot_2019-06-27_17-41-28](https://user-images.githubusercontent.com/226839/60280228-ce33db00-9902-11e9-82f2-64f6d16fa00d.png)

**Comment by HenriKorver** [comment]
This above link https://1561649037172-vng-staging.maykin.nl/zrc/api/v1/zaken brings me this result:
`The requested resource has been already turned off `

**Comment by alextreme** [comment]
My session from last week was stopped, if this happens you will need to start a new session (MOR sessie (zonder authenticatie)).

I've created a new one to verify this again: https://vng-staging.maykin.nl/08f92e26-b287-4eb5-83af-7f11b878b1c0/

https://1562256639114-vng-staging.maykin.nl/zrc/api/v1/zaken

I've also created #222 for Alvise to ensure other users can see the status of a consumer session, I noticed this was only clearly visible on the list-view

**Comment by alextreme** [comment]
An update on this, the above session was closed again.

@AlviseSembenico as discussed I remember that we only wanted to automatically close the sessions that were running on GCP (Docker or K8s sessions). The sessions like the one above (which run without a dedicated container) can keep on running and don't need to be closed on a daily basis (see the purge_sessions task in testsession app)

**Comment by alextreme** [comment]
Retesting this together with Henri, this is working fine with the 'MOR sessie (zonder authenticatie)' for the ZTC however for the ZRC we're getting 500-errors.

We'll wait until the ZRC RC-API environment is available and Sergei has given his blessing before retesting this.

**Comment by stevenbal** [comment]
I've tested this with the ZGW api's, and it appears to work. I've also added some functionality that creates the JWT token automatically from the SessionType.client_id and SessionType.secret upon saving the SessionType, and also adds it to the inject headers automatically (https://github.com/VNG-Realisatie/api-test-platform-code/pull/95)
