### ISSUE TITLE
Als gebruiker van een standaard wil ik dat de test voorziening een geimplementeerde API standaard ook semantisch test 

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/api-test-platform#88]
...zodat ik zeker weet dat een succesvolle compliancy test niet alleen betekent dat een correcte response gestuurd en ontvangen wordt maar dat de inhoud van het bericht ook semantisch voldoet aan het informatiemodel van de API.

**Toelichting**:
In het verledenis het vaak voorgekomen dat een geimplementeerde standaard weliswaar technisch correct was maar semantisch niet. Bijvoorbeeld in een zakLk01 waar een KVK nummer als extraElement opgevoerd is in plaats van als organisatie-identificatie. Een ander recent voorbeeld is de trouw-afspraak applicatie van de convenant gemeenten waar de eigenschappen zoals gedefinieerd in het zaaktype niet als zaakeigenschap in de ZRC ingestuurd worden maar als PDF in de DRC weggeschreven worden. 

Technisch voldoen aan een standaard is niet hetzelfde als semantisch voldoen aan een standaard.

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by HenriKorver** [comment]
Wat betreft het testen van een provider API is dit afgedekt. Immers je kunt de volledige kracht Postman-collections c.q. scripts gebruiken om alles te checken wat je maar nodig vindt, zowel technisch als semantisch.

Voor het testen van consumers is dat nog niet het geval. Nu kun je alleen technisch testen door te matchen op de requests die succesvol moeten verlopen. In issue #44 wordt dit opgelost door ook de kracht van Postman collections los te kunnen laten op consumers. Door middel van Postman-collections kunnen we straks de eindtoestand controleren die een consumer heeft achter gelaten bij de provider.

**Comment by HenriKorver** [comment]
@michielverhoef Is de bovenstaande uitleg voldoende om deze US af te kunnen sluiten?

**Comment by michielverhoef** [comment]
@HenriKorver Dank je, de uitleg is goed. Wat ik vanuit beheer echter graag zou willen is een voorbeeld van een inhoudelijke, semantische controle van zowel een provider als een consumer. Zodat we aan de ontwikkelaars van een standaard kunnen uitleggen (met voorbeeld) hoe dit werkt.

Misschien kunnen we daar binnenkort (maandag?) eens naar kijken, bijvoorbeeld met de demo API die we gebruiken voo rhet API beheer project?

**Comment by HenriKorver** [comment]
@michielverhoef We hebben inmiddels al een keer een demo gedaan. Kan ik m afsluiten?
