### ISSUE TITLE
Als API-beheerder wil ik een architectuur overzicht hebben van het testplatform

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/api-test-platform#93]
zodat ik belanghebbenden kan informeren hoe het testproces verloopt

**Toelichting**:
Met name het verschil tussen het testen van een consumer en een provider is belangrijk.

**Oplossingsrichting**:
Er zijn al diverse architectuurplaten van de testvoorziening. Deze moeten nog op goede manier in de documentatie worden opgenomen. Te beginnen met een mapje op github met de bestaande powerpoint presentaties etc.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by JanWillemKooi** [comment]
Henri heeft de procedure uitgelegd aan API beheerteam (@melsk-r @michielverhoef). Dit zou duidelijk moeten zijn zodat het API beheerteam dit in hun eigen procedures en documentatie kan opnemen.
