### ISSUE TITLE
Als API-beheerder wil ik een contact bij het API testplatform

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/api-test-platform#94]
zodat ik vragen kan stellen en eventuele problemen aan kan kaarten

**Toelichting**:
...

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by HenriKorver** [comment]
Als er vragen of problemen zijn kun je het best in eerste instantie een issue in deze repository inschieten. 
In tweede instantie kun je ook het slack kanaal `api-testvoorziening` gebruiken binnen `VNG Realisatie`
Als dat niet lukt of handig is kun je mij ook benaderen via mail, slack of mobiel.
